// Code generated by protoc-gen-go. DO NOT EDIT.
// source: faraday.proto

package frdrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Granularity describes the aggregation level at which the Bitcoin price should
//be queried. Note that setting lower levels of granularity may require more
//queries to the fiat backend.
type Granularity int32

const (
	Granularity_UNKNOWN_GRANULARITY Granularity = 0
	Granularity_MINUTE              Granularity = 1
	Granularity_FIVE_MINUTES        Granularity = 2
	Granularity_FIFTEEN_MINUTES     Granularity = 3
	Granularity_THIRTY_MINUTES      Granularity = 4
	Granularity_HOUR                Granularity = 5
	Granularity_SIX_HOURS           Granularity = 6
	Granularity_TWELVE_HOURS        Granularity = 7
	Granularity_DAY                 Granularity = 8
)

var Granularity_name = map[int32]string{
	0: "UNKNOWN_GRANULARITY",
	1: "MINUTE",
	2: "FIVE_MINUTES",
	3: "FIFTEEN_MINUTES",
	4: "THIRTY_MINUTES",
	5: "HOUR",
	6: "SIX_HOURS",
	7: "TWELVE_HOURS",
	8: "DAY",
}

var Granularity_value = map[string]int32{
	"UNKNOWN_GRANULARITY": 0,
	"MINUTE":              1,
	"FIVE_MINUTES":        2,
	"FIFTEEN_MINUTES":     3,
	"THIRTY_MINUTES":      4,
	"HOUR":                5,
	"SIX_HOURS":           6,
	"TWELVE_HOURS":        7,
	"DAY":                 8,
}

func (x Granularity) String() string {
	return proto.EnumName(Granularity_name, int32(x))
}

func (Granularity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{0}
}

type EntryType int32

const (
	EntryType_UNKNOWN EntryType = 0
	// A channel opening transaction for a channel opened by our node.
	EntryType_LOCAL_CHANNEL_OPEN EntryType = 1
	// A channel opening transaction for a channel opened by a remote node.
	EntryType_REMOTE_CHANNEL_OPEN EntryType = 2
	// The on chain fee paid to open a channel.
	EntryType_CHANNEL_OPEN_FEE EntryType = 3
	// A channel closing transaction.
	EntryType_CHANNEL_CLOSE EntryType = 4
	// Receipt of funds. On chain this reflects receives, off chain settlement
	// of invoices.
	EntryType_RECEIPT EntryType = 5
	// Payment of funds. On chain this reflects sends, off chain settlement
	// of our payments.
	EntryType_PAYMENT EntryType = 6
	// Payment of fees.
	EntryType_FEE EntryType = 7
	// Receipt of a payment to ourselves.
	EntryType_CIRCULAR_RECEIPT EntryType = 8
	// A forward through our node.
	EntryType_FORWARD EntryType = 9
	// Fees earned from forwarding.
	EntryType_FORWARD_FEE EntryType = 10
	// Sending of a payment to ourselves.
	EntryType_CIRCULAR_PAYMENT EntryType = 11
	// The fees paid to send an off chain payment to ourselves.
	EntryType_CIRCULAR_FEE EntryType = 12
	// A transaction that sweeps funds back into our wallet's control.
	EntryType_SWEEP EntryType = 13
	// The amount of fees paid for a sweep transaction.
	EntryType_SWEEP_FEE EntryType = 14
	// The fees paid to close a channel.
	EntryType_CHANNEL_CLOSE_FEE EntryType = 15
)

var EntryType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "LOCAL_CHANNEL_OPEN",
	2:  "REMOTE_CHANNEL_OPEN",
	3:  "CHANNEL_OPEN_FEE",
	4:  "CHANNEL_CLOSE",
	5:  "RECEIPT",
	6:  "PAYMENT",
	7:  "FEE",
	8:  "CIRCULAR_RECEIPT",
	9:  "FORWARD",
	10: "FORWARD_FEE",
	11: "CIRCULAR_PAYMENT",
	12: "CIRCULAR_FEE",
	13: "SWEEP",
	14: "SWEEP_FEE",
	15: "CHANNEL_CLOSE_FEE",
}

var EntryType_value = map[string]int32{
	"UNKNOWN":             0,
	"LOCAL_CHANNEL_OPEN":  1,
	"REMOTE_CHANNEL_OPEN": 2,
	"CHANNEL_OPEN_FEE":    3,
	"CHANNEL_CLOSE":       4,
	"RECEIPT":             5,
	"PAYMENT":             6,
	"FEE":                 7,
	"CIRCULAR_RECEIPT":    8,
	"FORWARD":             9,
	"FORWARD_FEE":         10,
	"CIRCULAR_PAYMENT":    11,
	"CIRCULAR_FEE":        12,
	"SWEEP":               13,
	"SWEEP_FEE":           14,
	"CHANNEL_CLOSE_FEE":   15,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}

func (EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{1}
}

type CloseRecommendationRequest_Metric int32

const (
	CloseRecommendationRequest_UNKNOWN         CloseRecommendationRequest_Metric = 0
	CloseRecommendationRequest_UPTIME          CloseRecommendationRequest_Metric = 1
	CloseRecommendationRequest_REVENUE         CloseRecommendationRequest_Metric = 2
	CloseRecommendationRequest_INCOMING_VOLUME CloseRecommendationRequest_Metric = 3
	CloseRecommendationRequest_OUTGOING_VOLUME CloseRecommendationRequest_Metric = 4
	CloseRecommendationRequest_TOTAL_VOLUME    CloseRecommendationRequest_Metric = 5
)

var CloseRecommendationRequest_Metric_name = map[int32]string{
	0: "UNKNOWN",
	1: "UPTIME",
	2: "REVENUE",
	3: "INCOMING_VOLUME",
	4: "OUTGOING_VOLUME",
	5: "TOTAL_VOLUME",
}

var CloseRecommendationRequest_Metric_value = map[string]int32{
	"UNKNOWN":         0,
	"UPTIME":          1,
	"REVENUE":         2,
	"INCOMING_VOLUME": 3,
	"OUTGOING_VOLUME": 4,
	"TOTAL_VOLUME":    5,
}

func (x CloseRecommendationRequest_Metric) String() string {
	return proto.EnumName(CloseRecommendationRequest_Metric_name, int32(x))
}

func (CloseRecommendationRequest_Metric) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{0, 0}
}

type CloseRecommendationRequest struct {
	//
	//The minimum amount of time in seconds that a channel should have been
	//monitored by lnd to be eligible for close. This value is in place to
	//protect against closing of newer channels.
	MinimumMonitored int64 `protobuf:"varint,1,opt,name=minimum_monitored,json=minimumMonitored,proto3" json:"minimum_monitored,omitempty"`
	//
	//The data point base close recommendations on. Available options are:
	//Uptime: ratio of channel peer's uptime to the period they have been
	//monitored to.
	//Revenue: the revenue that the channel has produced per block that its
	//funding transaction has been confirmed for.
	Metric               CloseRecommendationRequest_Metric `protobuf:"varint,2,opt,name=metric,proto3,enum=frdrpc.CloseRecommendationRequest_Metric" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CloseRecommendationRequest) Reset()         { *m = CloseRecommendationRequest{} }
func (m *CloseRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRecommendationRequest) ProtoMessage()    {}
func (*CloseRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{0}
}

func (m *CloseRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRecommendationRequest.Unmarshal(m, b)
}
func (m *CloseRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *CloseRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRecommendationRequest.Merge(m, src)
}
func (m *CloseRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRecommendationRequest.Size(m)
}
func (m *CloseRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRecommendationRequest proto.InternalMessageInfo

func (m *CloseRecommendationRequest) GetMinimumMonitored() int64 {
	if m != nil {
		return m.MinimumMonitored
	}
	return 0
}

func (m *CloseRecommendationRequest) GetMetric() CloseRecommendationRequest_Metric {
	if m != nil {
		return m.Metric
	}
	return CloseRecommendationRequest_UNKNOWN
}

type OutlierRecommendationsRequest struct {
	//
	//The parameters that are common to all close recommendations.
	RecRequest *CloseRecommendationRequest `protobuf:"bytes,1,opt,name=rec_request,json=recRequest,proto3" json:"rec_request,omitempty"`
	//
	//The number of inter-quartile ranges a value needs to be beneath the lower
	//quartile/ above the upper quartile to be considered a lower/upper outlier.
	//Lower values will be more aggressive in recommending channel closes, and
	//upper values will be more conservative. Recommended values are 1.5 for
	//aggressive recommendations and 3 for conservative recommendations.
	OutlierMultiplier    float32  `protobuf:"fixed32,2,opt,name=outlier_multiplier,json=outlierMultiplier,proto3" json:"outlier_multiplier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutlierRecommendationsRequest) Reset()         { *m = OutlierRecommendationsRequest{} }
func (m *OutlierRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*OutlierRecommendationsRequest) ProtoMessage()    {}
func (*OutlierRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{1}
}

func (m *OutlierRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutlierRecommendationsRequest.Unmarshal(m, b)
}
func (m *OutlierRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutlierRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *OutlierRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutlierRecommendationsRequest.Merge(m, src)
}
func (m *OutlierRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_OutlierRecommendationsRequest.Size(m)
}
func (m *OutlierRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutlierRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutlierRecommendationsRequest proto.InternalMessageInfo

func (m *OutlierRecommendationsRequest) GetRecRequest() *CloseRecommendationRequest {
	if m != nil {
		return m.RecRequest
	}
	return nil
}

func (m *OutlierRecommendationsRequest) GetOutlierMultiplier() float32 {
	if m != nil {
		return m.OutlierMultiplier
	}
	return 0
}

type ThresholdRecommendationsRequest struct {
	//
	//The parameters that are common to all close recommendations.
	RecRequest *CloseRecommendationRequest `protobuf:"bytes,1,opt,name=rec_request,json=recRequest,proto3" json:"rec_request,omitempty"`
	//
	//The threshold that recommendations will be calculated based on.
	//For uptime: ratio of uptime to observed lifetime beneath which channels
	//will be recommended for closure.
	//
	//For revenue: revenue per block that capital has been committed to the
	//channel beneath which channels will be recommended for closure. This
	//value is provided per block so that channels that have been open for
	//different periods of time can be compared.
	//
	//For incoming volume: The incoming volume per block that capital has
	//been committed to the channel beneath which channels will be recommended
	//for closure. This value is provided per block so that channels that have
	//been open for different periods of time can be compared.
	//
	//For outgoing volume: The outgoing volume per block that capital has been
	//committed to the channel beneath which channels will be recommended for
	//closure. This value is provided per block so that channels that have been
	//open for different periods of time can be compared.
	//
	//For total volume: The total volume per block that capital has been
	//committed to the channel beneath which channels will be recommended for
	//closure. This value is provided per block so that channels that have been
	//open for different periods of time can be compared.
	ThresholdValue       float32  `protobuf:"fixed32,2,opt,name=threshold_value,json=thresholdValue,proto3" json:"threshold_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThresholdRecommendationsRequest) Reset()         { *m = ThresholdRecommendationsRequest{} }
func (m *ThresholdRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ThresholdRecommendationsRequest) ProtoMessage()    {}
func (*ThresholdRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{2}
}

func (m *ThresholdRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Unmarshal(m, b)
}
func (m *ThresholdRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ThresholdRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdRecommendationsRequest.Merge(m, src)
}
func (m *ThresholdRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Size(m)
}
func (m *ThresholdRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdRecommendationsRequest proto.InternalMessageInfo

func (m *ThresholdRecommendationsRequest) GetRecRequest() *CloseRecommendationRequest {
	if m != nil {
		return m.RecRequest
	}
	return nil
}

func (m *ThresholdRecommendationsRequest) GetThresholdValue() float32 {
	if m != nil {
		return m.ThresholdValue
	}
	return 0
}

type CloseRecommendationsResponse struct {
	//
	//The total number of channels, before filtering out channels that are
	//not eligible for close recommendations.
	TotalChannels int32 `protobuf:"varint,1,opt,name=total_channels,json=totalChannels,proto3" json:"total_channels,omitempty"`
	//
	//The number of channels that were considered for close recommendations.
	ConsideredChannels int32 `protobuf:"varint,2,opt,name=considered_channels,json=consideredChannels,proto3" json:"considered_channels,omitempty"`
	//
	//A set of channel close recommendations. The absence of a channel in this
	//set implies that it was not considered for close because it did not meet
	//the criteria for close recommendations (it is private, or has not been
	//monitored for long enough).
	Recommendations      []*Recommendation `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CloseRecommendationsResponse) Reset()         { *m = CloseRecommendationsResponse{} }
func (m *CloseRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*CloseRecommendationsResponse) ProtoMessage()    {}
func (*CloseRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{3}
}

func (m *CloseRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRecommendationsResponse.Unmarshal(m, b)
}
func (m *CloseRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *CloseRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRecommendationsResponse.Merge(m, src)
}
func (m *CloseRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_CloseRecommendationsResponse.Size(m)
}
func (m *CloseRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRecommendationsResponse proto.InternalMessageInfo

func (m *CloseRecommendationsResponse) GetTotalChannels() int32 {
	if m != nil {
		return m.TotalChannels
	}
	return 0
}

func (m *CloseRecommendationsResponse) GetConsideredChannels() int32 {
	if m != nil {
		return m.ConsideredChannels
	}
	return 0
}

func (m *CloseRecommendationsResponse) GetRecommendations() []*Recommendation {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

type Recommendation struct {
	//
	//The channel point [funding txid: outpoint] of the channel being considered
	//for close.
	ChanPoint string `protobuf:"bytes,1,opt,name=chan_point,json=chanPoint,proto3" json:"chan_point,omitempty"`
	// The value of the metric that close recommendations were based on.
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// A boolean indicating whether we recommend closing the channel.
	RecommendClose       bool     `protobuf:"varint,3,opt,name=recommend_close,json=recommendClose,proto3" json:"recommend_close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recommendation) Reset()         { *m = Recommendation{} }
func (m *Recommendation) String() string { return proto.CompactTextString(m) }
func (*Recommendation) ProtoMessage()    {}
func (*Recommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{4}
}

func (m *Recommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation.Unmarshal(m, b)
}
func (m *Recommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation.Merge(m, src)
}
func (m *Recommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation.Size(m)
}
func (m *Recommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation proto.InternalMessageInfo

func (m *Recommendation) GetChanPoint() string {
	if m != nil {
		return m.ChanPoint
	}
	return ""
}

func (m *Recommendation) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Recommendation) GetRecommendClose() bool {
	if m != nil {
		return m.RecommendClose
	}
	return false
}

type RevenueReportRequest struct {
	//
	//The funding transaction outpoints for the channels to generate a revenue
	//report for. If this is empty, it will be generated for all open and closed
	//channels. Channel funding points should be expressed with the format
	//fundingTxID:outpoint.
	ChanPoints []string `protobuf:"bytes,1,rep,name=chan_points,json=chanPoints,proto3" json:"chan_points,omitempty"`
	//
	//Start time is beginning of the range over which the report will be
	//generated, expressed as unix epoch offset in seconds.
	StartTime uint64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	//
	//End time is end of the range over which the report will be
	//generated, expressed as unix epoch offset in seconds.
	EndTime              uint64   `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevenueReportRequest) Reset()         { *m = RevenueReportRequest{} }
func (m *RevenueReportRequest) String() string { return proto.CompactTextString(m) }
func (*RevenueReportRequest) ProtoMessage()    {}
func (*RevenueReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{5}
}

func (m *RevenueReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReportRequest.Unmarshal(m, b)
}
func (m *RevenueReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReportRequest.Marshal(b, m, deterministic)
}
func (m *RevenueReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReportRequest.Merge(m, src)
}
func (m *RevenueReportRequest) XXX_Size() int {
	return xxx_messageInfo_RevenueReportRequest.Size(m)
}
func (m *RevenueReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReportRequest proto.InternalMessageInfo

func (m *RevenueReportRequest) GetChanPoints() []string {
	if m != nil {
		return m.ChanPoints
	}
	return nil
}

func (m *RevenueReportRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RevenueReportRequest) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type RevenueReportResponse struct {
	//
	//Reports is a set of pairwise revenue report generated for the channel(s)
	//over the period specified.
	Reports              []*RevenueReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RevenueReportResponse) Reset()         { *m = RevenueReportResponse{} }
func (m *RevenueReportResponse) String() string { return proto.CompactTextString(m) }
func (*RevenueReportResponse) ProtoMessage()    {}
func (*RevenueReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{6}
}

func (m *RevenueReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReportResponse.Unmarshal(m, b)
}
func (m *RevenueReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReportResponse.Marshal(b, m, deterministic)
}
func (m *RevenueReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReportResponse.Merge(m, src)
}
func (m *RevenueReportResponse) XXX_Size() int {
	return xxx_messageInfo_RevenueReportResponse.Size(m)
}
func (m *RevenueReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReportResponse proto.InternalMessageInfo

func (m *RevenueReportResponse) GetReports() []*RevenueReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

type RevenueReport struct {
	//
	//Target channel is the channel that the report is generated for; incoming
	//fields in the report mean that this channel was the incoming channel,
	//and the pair as the outgoing, outgoing fields mean that this channel was
	//the outgoing channel and the peer was the incoming channel.
	TargetChannel string `protobuf:"bytes,1,opt,name=target_channel,json=targetChannel,proto3" json:"target_channel,omitempty"`
	//
	//Pair reports maps the channel point of a peer that we generated revenue
	//with to a report detailing the revenue.
	PairReports          map[string]*PairReport `protobuf:"bytes,2,rep,name=pair_reports,json=pairReports,proto3" json:"pair_reports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RevenueReport) Reset()         { *m = RevenueReport{} }
func (m *RevenueReport) String() string { return proto.CompactTextString(m) }
func (*RevenueReport) ProtoMessage()    {}
func (*RevenueReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{7}
}

func (m *RevenueReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReport.Unmarshal(m, b)
}
func (m *RevenueReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReport.Marshal(b, m, deterministic)
}
func (m *RevenueReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReport.Merge(m, src)
}
func (m *RevenueReport) XXX_Size() int {
	return xxx_messageInfo_RevenueReport.Size(m)
}
func (m *RevenueReport) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReport.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReport proto.InternalMessageInfo

func (m *RevenueReport) GetTargetChannel() string {
	if m != nil {
		return m.TargetChannel
	}
	return ""
}

func (m *RevenueReport) GetPairReports() map[string]*PairReport {
	if m != nil {
		return m.PairReports
	}
	return nil
}

type PairReport struct {
	//
	//Amount outgoing msat is the amount in millisatoshis that arrived
	//on the pair channel to be forwarded onwards by our channel.
	AmountOutgoingMsat int64 `protobuf:"varint,1,opt,name=amount_outgoing_msat,json=amountOutgoingMsat,proto3" json:"amount_outgoing_msat,omitempty"`
	//
	//Fees outgoing is the amount of fees in millisatoshis that we
	//attribute to the channel for its role as the outgoing channel in
	//forwards.
	FeesOutgoingMsat int64 `protobuf:"varint,2,opt,name=fees_outgoing_msat,json=feesOutgoingMsat,proto3" json:"fees_outgoing_msat,omitempty"`
	//
	//Amount incoming msat is the amount in millisatoshis that arrived
	//on our channel to be forwarded onwards by the pair channel.
	AmountIncomingMsat int64 `protobuf:"varint,3,opt,name=amount_incoming_msat,json=amountIncomingMsat,proto3" json:"amount_incoming_msat,omitempty"`
	//
	//Fees incoming is the amount of fees in millisatoshis that we
	//attribute to the channel for its role as the incoming channel in
	//forwards.
	FeesIncomingMsat     int64    `protobuf:"varint,4,opt,name=fees_incoming_msat,json=feesIncomingMsat,proto3" json:"fees_incoming_msat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairReport) Reset()         { *m = PairReport{} }
func (m *PairReport) String() string { return proto.CompactTextString(m) }
func (*PairReport) ProtoMessage()    {}
func (*PairReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{8}
}

func (m *PairReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairReport.Unmarshal(m, b)
}
func (m *PairReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairReport.Marshal(b, m, deterministic)
}
func (m *PairReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairReport.Merge(m, src)
}
func (m *PairReport) XXX_Size() int {
	return xxx_messageInfo_PairReport.Size(m)
}
func (m *PairReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PairReport.DiscardUnknown(m)
}

var xxx_messageInfo_PairReport proto.InternalMessageInfo

func (m *PairReport) GetAmountOutgoingMsat() int64 {
	if m != nil {
		return m.AmountOutgoingMsat
	}
	return 0
}

func (m *PairReport) GetFeesOutgoingMsat() int64 {
	if m != nil {
		return m.FeesOutgoingMsat
	}
	return 0
}

func (m *PairReport) GetAmountIncomingMsat() int64 {
	if m != nil {
		return m.AmountIncomingMsat
	}
	return 0
}

func (m *PairReport) GetFeesIncomingMsat() int64 {
	if m != nil {
		return m.FeesIncomingMsat
	}
	return 0
}

type ChannelInsightsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInsightsRequest) Reset()         { *m = ChannelInsightsRequest{} }
func (m *ChannelInsightsRequest) String() string { return proto.CompactTextString(m) }
func (*ChannelInsightsRequest) ProtoMessage()    {}
func (*ChannelInsightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{9}
}

func (m *ChannelInsightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsightsRequest.Unmarshal(m, b)
}
func (m *ChannelInsightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsightsRequest.Marshal(b, m, deterministic)
}
func (m *ChannelInsightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsightsRequest.Merge(m, src)
}
func (m *ChannelInsightsRequest) XXX_Size() int {
	return xxx_messageInfo_ChannelInsightsRequest.Size(m)
}
func (m *ChannelInsightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsightsRequest proto.InternalMessageInfo

type ChannelInsightsResponse struct {
	// Insights for the set of currently open channels.
	ChannelInsights      []*ChannelInsight `protobuf:"bytes,1,rep,name=channel_insights,json=channelInsights,proto3" json:"channel_insights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelInsightsResponse) Reset()         { *m = ChannelInsightsResponse{} }
func (m *ChannelInsightsResponse) String() string { return proto.CompactTextString(m) }
func (*ChannelInsightsResponse) ProtoMessage()    {}
func (*ChannelInsightsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{10}
}

func (m *ChannelInsightsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsightsResponse.Unmarshal(m, b)
}
func (m *ChannelInsightsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsightsResponse.Marshal(b, m, deterministic)
}
func (m *ChannelInsightsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsightsResponse.Merge(m, src)
}
func (m *ChannelInsightsResponse) XXX_Size() int {
	return xxx_messageInfo_ChannelInsightsResponse.Size(m)
}
func (m *ChannelInsightsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsightsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsightsResponse proto.InternalMessageInfo

func (m *ChannelInsightsResponse) GetChannelInsights() []*ChannelInsight {
	if m != nil {
		return m.ChannelInsights
	}
	return nil
}

type ChannelInsight struct {
	// The outpoint of the channel's funding transaction.
	ChanPoint string `protobuf:"bytes,1,opt,name=chan_point,json=chanPoint,proto3" json:"chan_point,omitempty"`
	//
	//The amount of time in seconds that we have monitored the channel peer's
	//uptime for.
	MonitoredSeconds uint64 `protobuf:"varint,2,opt,name=monitored_seconds,json=monitoredSeconds,proto3" json:"monitored_seconds,omitempty"`
	//
	//The amount of time in seconds that the channel peer has been online over
	//the period it has been monitored for.
	UptimeSeconds uint64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	//
	//The volume, in millisatoshis, that has been forwarded with this channel as
	//the incoming channel.
	VolumeIncomingMsat int64 `protobuf:"varint,4,opt,name=volume_incoming_msat,json=volumeIncomingMsat,proto3" json:"volume_incoming_msat,omitempty"`
	//
	//The volume, in millisatoshis, that has been forwarded with this channel as
	//the outgoing channel.
	VolumeOutgoingMsat int64 `protobuf:"varint,5,opt,name=volume_outgoing_msat,json=volumeOutgoingMsat,proto3" json:"volume_outgoing_msat,omitempty"`
	//
	//The total fees earned by this channel for its participation in forwards,
	//expressed in millisatoshis. Note that we attribute fees evenly across
	//incoming and outgoing channels.
	FeesEarnedMsat int64 `protobuf:"varint,6,opt,name=fees_earned_msat,json=feesEarnedMsat,proto3" json:"fees_earned_msat,omitempty"`
	// The number of confirmations the funding transaction has.
	Confirmations uint32 `protobuf:"varint,7,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	// True if the channel is private.
	Private              bool     `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInsight) Reset()         { *m = ChannelInsight{} }
func (m *ChannelInsight) String() string { return proto.CompactTextString(m) }
func (*ChannelInsight) ProtoMessage()    {}
func (*ChannelInsight) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{11}
}

func (m *ChannelInsight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsight.Unmarshal(m, b)
}
func (m *ChannelInsight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsight.Marshal(b, m, deterministic)
}
func (m *ChannelInsight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsight.Merge(m, src)
}
func (m *ChannelInsight) XXX_Size() int {
	return xxx_messageInfo_ChannelInsight.Size(m)
}
func (m *ChannelInsight) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsight.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsight proto.InternalMessageInfo

func (m *ChannelInsight) GetChanPoint() string {
	if m != nil {
		return m.ChanPoint
	}
	return ""
}

func (m *ChannelInsight) GetMonitoredSeconds() uint64 {
	if m != nil {
		return m.MonitoredSeconds
	}
	return 0
}

func (m *ChannelInsight) GetUptimeSeconds() uint64 {
	if m != nil {
		return m.UptimeSeconds
	}
	return 0
}

func (m *ChannelInsight) GetVolumeIncomingMsat() int64 {
	if m != nil {
		return m.VolumeIncomingMsat
	}
	return 0
}

func (m *ChannelInsight) GetVolumeOutgoingMsat() int64 {
	if m != nil {
		return m.VolumeOutgoingMsat
	}
	return 0
}

func (m *ChannelInsight) GetFeesEarnedMsat() int64 {
	if m != nil {
		return m.FeesEarnedMsat
	}
	return 0
}

func (m *ChannelInsight) GetConfirmations() uint32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *ChannelInsight) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type ExchangeRateRequest struct {
	// A set of timestamps for which we want the bitcoin price.
	Timestamps []uint64 `protobuf:"varint,3,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	// The level of granularity at which we want the bitcoin price to be quoted.
	Granularity          Granularity `protobuf:"varint,4,opt,name=granularity,proto3,enum=frdrpc.Granularity" json:"granularity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ExchangeRateRequest) Reset()         { *m = ExchangeRateRequest{} }
func (m *ExchangeRateRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeRateRequest) ProtoMessage()    {}
func (*ExchangeRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{12}
}

func (m *ExchangeRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRateRequest.Unmarshal(m, b)
}
func (m *ExchangeRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRateRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRateRequest.Merge(m, src)
}
func (m *ExchangeRateRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeRateRequest.Size(m)
}
func (m *ExchangeRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRateRequest proto.InternalMessageInfo

func (m *ExchangeRateRequest) GetTimestamps() []uint64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *ExchangeRateRequest) GetGranularity() Granularity {
	if m != nil {
		return m.Granularity
	}
	return Granularity_UNKNOWN_GRANULARITY
}

type ExchangeRateResponse struct {
	// Rates contains a set of exchange rates for the set of timestamps
	Rates                []*ExchangeRate `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExchangeRateResponse) Reset()         { *m = ExchangeRateResponse{} }
func (m *ExchangeRateResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeRateResponse) ProtoMessage()    {}
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{13}
}

func (m *ExchangeRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRateResponse.Unmarshal(m, b)
}
func (m *ExchangeRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRateResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRateResponse.Merge(m, src)
}
func (m *ExchangeRateResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeRateResponse.Size(m)
}
func (m *ExchangeRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRateResponse proto.InternalMessageInfo

func (m *ExchangeRateResponse) GetRates() []*ExchangeRate {
	if m != nil {
		return m.Rates
	}
	return nil
}

type BitcoinPrice struct {
	// The price of 1 BTC, expressed in USD.
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// The timestamp for this price price provided.
	PriceTimestamp       uint64   `protobuf:"varint,2,opt,name=price_timestamp,json=priceTimestamp,proto3" json:"price_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitcoinPrice) Reset()         { *m = BitcoinPrice{} }
func (m *BitcoinPrice) String() string { return proto.CompactTextString(m) }
func (*BitcoinPrice) ProtoMessage()    {}
func (*BitcoinPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{14}
}

func (m *BitcoinPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitcoinPrice.Unmarshal(m, b)
}
func (m *BitcoinPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitcoinPrice.Marshal(b, m, deterministic)
}
func (m *BitcoinPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoinPrice.Merge(m, src)
}
func (m *BitcoinPrice) XXX_Size() int {
	return xxx_messageInfo_BitcoinPrice.Size(m)
}
func (m *BitcoinPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoinPrice.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoinPrice proto.InternalMessageInfo

func (m *BitcoinPrice) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *BitcoinPrice) GetPriceTimestamp() uint64 {
	if m != nil {
		return m.PriceTimestamp
	}
	return 0
}

type ExchangeRate struct {
	// timestamp is the timestamp of the original request made.
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	//
	//Price is the bitcoin price approximation for the timestamp queried. Note
	//that this value has its own timestamp because we are not guaranteed to get
	//price points for the exact timestamp that was queried.
	BtcPrice             *BitcoinPrice `protobuf:"bytes,2,opt,name=btc_price,json=btcPrice,proto3" json:"btc_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExchangeRate) Reset()         { *m = ExchangeRate{} }
func (m *ExchangeRate) String() string { return proto.CompactTextString(m) }
func (*ExchangeRate) ProtoMessage()    {}
func (*ExchangeRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{15}
}

func (m *ExchangeRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRate.Unmarshal(m, b)
}
func (m *ExchangeRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRate.Marshal(b, m, deterministic)
}
func (m *ExchangeRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRate.Merge(m, src)
}
func (m *ExchangeRate) XXX_Size() int {
	return xxx_messageInfo_ExchangeRate.Size(m)
}
func (m *ExchangeRate) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRate.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRate proto.InternalMessageInfo

func (m *ExchangeRate) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ExchangeRate) GetBtcPrice() *BitcoinPrice {
	if m != nil {
		return m.BtcPrice
	}
	return nil
}

type NodeAuditRequest struct {
	// The unix time from which to produce the report, inclusive.
	StartTime uint64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The unix time until which to produce the report, exclusive.
	EndTime uint64 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	//
	//Set to generate a report without conversion to fiat. If set, fiat values
	//will display as 0.
	DisableFiat bool `protobuf:"varint,4,opt,name=disable_fiat,json=disableFiat,proto3" json:"disable_fiat,omitempty"`
	// The level of granularity at which we wish to produce fiat prices.
	Granularity Granularity `protobuf:"varint,5,opt,name=granularity,proto3,enum=frdrpc.Granularity" json:"granularity,omitempty"`
	//
	//An optional set of custom categories which can be used to identify bespoke
	//categories in the report. Each category must have a unique name, and may not
	//have common identifier regexes. Transactions that are matched to these
	//categories report the category name in the CustomCategory field.
	CustomCategories     []*CustomCategory `protobuf:"bytes,6,rep,name=custom_categories,json=customCategories,proto3" json:"custom_categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeAuditRequest) Reset()         { *m = NodeAuditRequest{} }
func (m *NodeAuditRequest) String() string { return proto.CompactTextString(m) }
func (*NodeAuditRequest) ProtoMessage()    {}
func (*NodeAuditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{16}
}

func (m *NodeAuditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAuditRequest.Unmarshal(m, b)
}
func (m *NodeAuditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAuditRequest.Marshal(b, m, deterministic)
}
func (m *NodeAuditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAuditRequest.Merge(m, src)
}
func (m *NodeAuditRequest) XXX_Size() int {
	return xxx_messageInfo_NodeAuditRequest.Size(m)
}
func (m *NodeAuditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAuditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAuditRequest proto.InternalMessageInfo

func (m *NodeAuditRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *NodeAuditRequest) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *NodeAuditRequest) GetDisableFiat() bool {
	if m != nil {
		return m.DisableFiat
	}
	return false
}

func (m *NodeAuditRequest) GetGranularity() Granularity {
	if m != nil {
		return m.Granularity
	}
	return Granularity_UNKNOWN_GRANULARITY
}

func (m *NodeAuditRequest) GetCustomCategories() []*CustomCategory {
	if m != nil {
		return m.CustomCategories
	}
	return nil
}

type CustomCategory struct {
	//
	//The name for the custom category which will contain all transactions that
	//are labelled with a string matching one of the regexes provided in
	//label identifiers.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//
	//Set to true to apply this category to on chain transactions. Can be set in
	//conjunction with off_chain to apply the category to all transactions.
	OnChain bool `protobuf:"varint,2,opt,name=on_chain,json=onChain,proto3" json:"on_chain,omitempty"`
	//
	//Set to true to apply this category to off chain transactions. Can be set in
	//conjunction with on_chain to apply the category to all transactions.
	OffChain bool `protobuf:"varint,3,opt,name=off_chain,json=offChain,proto3" json:"off_chain,omitempty"`
	//
	//A set of regular expressions which identify transactions by their label as
	//belonging in this custom category. If a label matches any single regex in
	//the set, it is considered to be in the category. These expressions will be
	//matched against various labels that are present in lnd: on chain
	//transactions will be matched against their label field, off chain receipts
	//will be matched against their memo. At present, there is no way to match
	//forwards or off chain payments. These expressions must be unique across
	//custom categories, otherwise faraday will not be able to identify which
	//custom category a transaction belongs in.
	LabelPatterns        []string `protobuf:"bytes,5,rep,name=label_patterns,json=labelPatterns,proto3" json:"label_patterns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomCategory) Reset()         { *m = CustomCategory{} }
func (m *CustomCategory) String() string { return proto.CompactTextString(m) }
func (*CustomCategory) ProtoMessage()    {}
func (*CustomCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{17}
}

func (m *CustomCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomCategory.Unmarshal(m, b)
}
func (m *CustomCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomCategory.Marshal(b, m, deterministic)
}
func (m *CustomCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomCategory.Merge(m, src)
}
func (m *CustomCategory) XXX_Size() int {
	return xxx_messageInfo_CustomCategory.Size(m)
}
func (m *CustomCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomCategory.DiscardUnknown(m)
}

var xxx_messageInfo_CustomCategory proto.InternalMessageInfo

func (m *CustomCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomCategory) GetOnChain() bool {
	if m != nil {
		return m.OnChain
	}
	return false
}

func (m *CustomCategory) GetOffChain() bool {
	if m != nil {
		return m.OffChain
	}
	return false
}

func (m *CustomCategory) GetLabelPatterns() []string {
	if m != nil {
		return m.LabelPatterns
	}
	return nil
}

type ReportEntry struct {
	// The unix timestamp of the event.
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Whether the entry occurred on chain or off chain.
	OnChain bool `protobuf:"varint,2,opt,name=on_chain,json=onChain,proto3" json:"on_chain,omitempty"`
	// The amount of the entry, expressed in millisatoshis.
	Amount uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Whether the entry is a credit or a debit.
	Credit bool `protobuf:"varint,4,opt,name=credit,proto3" json:"credit,omitempty"`
	// The asset affected by the entry.
	Asset string `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	// The kind of activity that this entry represents.
	Type EntryType `protobuf:"varint,6,opt,name=type,proto3,enum=frdrpc.EntryType" json:"type,omitempty"`
	//
	//This field will be populated for entry type custom, and represents the name
	//of a custom category that the report was produced with.
	CustomCategory string `protobuf:"bytes,12,opt,name=custom_category,json=customCategory,proto3" json:"custom_category,omitempty"`
	// The transaction id of the entry.
	Txid string `protobuf:"bytes,7,opt,name=txid,proto3" json:"txid,omitempty"`
	// The fiat amount of the entry's amount in USD.
	Fiat string `protobuf:"bytes,8,opt,name=fiat,proto3" json:"fiat,omitempty"`
	// A unique identifier for the entry, if available.
	Reference string `protobuf:"bytes,9,opt,name=reference,proto3" json:"reference,omitempty"`
	// An additional note for the entry, providing additional context.
	Note string `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	// The bitcoin price and timestamp used to calcualte our fiat value.
	BtcPrice             *BitcoinPrice `protobuf:"bytes,11,opt,name=btc_price,json=btcPrice,proto3" json:"btc_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReportEntry) Reset()         { *m = ReportEntry{} }
func (m *ReportEntry) String() string { return proto.CompactTextString(m) }
func (*ReportEntry) ProtoMessage()    {}
func (*ReportEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{18}
}

func (m *ReportEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportEntry.Unmarshal(m, b)
}
func (m *ReportEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportEntry.Marshal(b, m, deterministic)
}
func (m *ReportEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportEntry.Merge(m, src)
}
func (m *ReportEntry) XXX_Size() int {
	return xxx_messageInfo_ReportEntry.Size(m)
}
func (m *ReportEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ReportEntry proto.InternalMessageInfo

func (m *ReportEntry) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReportEntry) GetOnChain() bool {
	if m != nil {
		return m.OnChain
	}
	return false
}

func (m *ReportEntry) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReportEntry) GetCredit() bool {
	if m != nil {
		return m.Credit
	}
	return false
}

func (m *ReportEntry) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ReportEntry) GetType() EntryType {
	if m != nil {
		return m.Type
	}
	return EntryType_UNKNOWN
}

func (m *ReportEntry) GetCustomCategory() string {
	if m != nil {
		return m.CustomCategory
	}
	return ""
}

func (m *ReportEntry) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ReportEntry) GetFiat() string {
	if m != nil {
		return m.Fiat
	}
	return ""
}

func (m *ReportEntry) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *ReportEntry) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ReportEntry) GetBtcPrice() *BitcoinPrice {
	if m != nil {
		return m.BtcPrice
	}
	return nil
}

type NodeAuditResponse struct {
	// On chain reports for the period queried.
	Reports              []*ReportEntry `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeAuditResponse) Reset()         { *m = NodeAuditResponse{} }
func (m *NodeAuditResponse) String() string { return proto.CompactTextString(m) }
func (*NodeAuditResponse) ProtoMessage()    {}
func (*NodeAuditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{19}
}

func (m *NodeAuditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAuditResponse.Unmarshal(m, b)
}
func (m *NodeAuditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAuditResponse.Marshal(b, m, deterministic)
}
func (m *NodeAuditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAuditResponse.Merge(m, src)
}
func (m *NodeAuditResponse) XXX_Size() int {
	return xxx_messageInfo_NodeAuditResponse.Size(m)
}
func (m *NodeAuditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAuditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAuditResponse proto.InternalMessageInfo

func (m *NodeAuditResponse) GetReports() []*ReportEntry {
	if m != nil {
		return m.Reports
	}
	return nil
}

type CloseReportRequest struct {
	//
	//The funding outpoint of the channel the report should be created for,
	//formatted txid:outpoint.
	ChannelPoint         string   `protobuf:"bytes,1,opt,name=channel_point,json=channelPoint,proto3" json:"channel_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseReportRequest) Reset()         { *m = CloseReportRequest{} }
func (m *CloseReportRequest) String() string { return proto.CompactTextString(m) }
func (*CloseReportRequest) ProtoMessage()    {}
func (*CloseReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{20}
}

func (m *CloseReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseReportRequest.Unmarshal(m, b)
}
func (m *CloseReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseReportRequest.Marshal(b, m, deterministic)
}
func (m *CloseReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseReportRequest.Merge(m, src)
}
func (m *CloseReportRequest) XXX_Size() int {
	return xxx_messageInfo_CloseReportRequest.Size(m)
}
func (m *CloseReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseReportRequest proto.InternalMessageInfo

func (m *CloseReportRequest) GetChannelPoint() string {
	if m != nil {
		return m.ChannelPoint
	}
	return ""
}

type CloseReportResponse struct {
	// The funding outpoint of the channel.
	ChannelPoint string `protobuf:"bytes,1,opt,name=channel_point,json=channelPoint,proto3" json:"channel_point,omitempty"`
	// True if we opened the channel, false if the remote peer did.
	ChannelInitiator bool `protobuf:"varint,2,opt,name=channel_initiator,json=channelInitiator,proto3" json:"channel_initiator,omitempty"`
	// The type of close that resolved this channel.
	CloseType string `protobuf:"bytes,3,opt,name=close_type,json=closeType,proto3" json:"close_type,omitempty"`
	// The transaction id of the close transaction that confirmed on chain.
	CloseTxid string `protobuf:"bytes,4,opt,name=close_txid,json=closeTxid,proto3" json:"close_txid,omitempty"`
	//
	//The fee we paid on chain to open this channel in satoshis, note that this
	//field will be zero if the remote party paid.
	OpenFee string `protobuf:"bytes,5,opt,name=open_fee,json=openFee,proto3" json:"open_fee,omitempty"`
	//
	//The fee we paid on chain for the close transaction in staoshis, note that
	//this field will be zero if the remote party paid.
	CloseFee             string   `protobuf:"bytes,6,opt,name=close_fee,json=closeFee,proto3" json:"close_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseReportResponse) Reset()         { *m = CloseReportResponse{} }
func (m *CloseReportResponse) String() string { return proto.CompactTextString(m) }
func (*CloseReportResponse) ProtoMessage()    {}
func (*CloseReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ccb88e279ed9462, []int{21}
}

func (m *CloseReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseReportResponse.Unmarshal(m, b)
}
func (m *CloseReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseReportResponse.Marshal(b, m, deterministic)
}
func (m *CloseReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseReportResponse.Merge(m, src)
}
func (m *CloseReportResponse) XXX_Size() int {
	return xxx_messageInfo_CloseReportResponse.Size(m)
}
func (m *CloseReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseReportResponse proto.InternalMessageInfo

func (m *CloseReportResponse) GetChannelPoint() string {
	if m != nil {
		return m.ChannelPoint
	}
	return ""
}

func (m *CloseReportResponse) GetChannelInitiator() bool {
	if m != nil {
		return m.ChannelInitiator
	}
	return false
}

func (m *CloseReportResponse) GetCloseType() string {
	if m != nil {
		return m.CloseType
	}
	return ""
}

func (m *CloseReportResponse) GetCloseTxid() string {
	if m != nil {
		return m.CloseTxid
	}
	return ""
}

func (m *CloseReportResponse) GetOpenFee() string {
	if m != nil {
		return m.OpenFee
	}
	return ""
}

func (m *CloseReportResponse) GetCloseFee() string {
	if m != nil {
		return m.CloseFee
	}
	return ""
}

func init() {
	proto.RegisterEnum("frdrpc.Granularity", Granularity_name, Granularity_value)
	proto.RegisterEnum("frdrpc.EntryType", EntryType_name, EntryType_value)
	proto.RegisterEnum("frdrpc.CloseRecommendationRequest_Metric", CloseRecommendationRequest_Metric_name, CloseRecommendationRequest_Metric_value)
	proto.RegisterType((*CloseRecommendationRequest)(nil), "frdrpc.CloseRecommendationRequest")
	proto.RegisterType((*OutlierRecommendationsRequest)(nil), "frdrpc.OutlierRecommendationsRequest")
	proto.RegisterType((*ThresholdRecommendationsRequest)(nil), "frdrpc.ThresholdRecommendationsRequest")
	proto.RegisterType((*CloseRecommendationsResponse)(nil), "frdrpc.CloseRecommendationsResponse")
	proto.RegisterType((*Recommendation)(nil), "frdrpc.Recommendation")
	proto.RegisterType((*RevenueReportRequest)(nil), "frdrpc.RevenueReportRequest")
	proto.RegisterType((*RevenueReportResponse)(nil), "frdrpc.RevenueReportResponse")
	proto.RegisterType((*RevenueReport)(nil), "frdrpc.RevenueReport")
	proto.RegisterMapType((map[string]*PairReport)(nil), "frdrpc.RevenueReport.PairReportsEntry")
	proto.RegisterType((*PairReport)(nil), "frdrpc.PairReport")
	proto.RegisterType((*ChannelInsightsRequest)(nil), "frdrpc.ChannelInsightsRequest")
	proto.RegisterType((*ChannelInsightsResponse)(nil), "frdrpc.ChannelInsightsResponse")
	proto.RegisterType((*ChannelInsight)(nil), "frdrpc.ChannelInsight")
	proto.RegisterType((*ExchangeRateRequest)(nil), "frdrpc.ExchangeRateRequest")
	proto.RegisterType((*ExchangeRateResponse)(nil), "frdrpc.ExchangeRateResponse")
	proto.RegisterType((*BitcoinPrice)(nil), "frdrpc.BitcoinPrice")
	proto.RegisterType((*ExchangeRate)(nil), "frdrpc.ExchangeRate")
	proto.RegisterType((*NodeAuditRequest)(nil), "frdrpc.NodeAuditRequest")
	proto.RegisterType((*CustomCategory)(nil), "frdrpc.CustomCategory")
	proto.RegisterType((*ReportEntry)(nil), "frdrpc.ReportEntry")
	proto.RegisterType((*NodeAuditResponse)(nil), "frdrpc.NodeAuditResponse")
	proto.RegisterType((*CloseReportRequest)(nil), "frdrpc.CloseReportRequest")
	proto.RegisterType((*CloseReportResponse)(nil), "frdrpc.CloseReportResponse")
}

func init() { proto.RegisterFile("faraday.proto", fileDescriptor_9ccb88e279ed9462) }

var fileDescriptor_9ccb88e279ed9462 = []byte{
	// 1802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x72, 0x23, 0x49,
	0x11, 0xa6, 0xf5, 0xaf, 0xd4, 0x8f, 0xdb, 0x65, 0x8f, 0x57, 0xeb, 0x99, 0xd9, 0x31, 0xcd, 0x0e,
	0xe3, 0x1d, 0x58, 0x7b, 0x31, 0x41, 0x04, 0x70, 0x5a, 0x8d, 0xb6, 0x35, 0xd6, 0xa2, 0xbf, 0x28,
	0xcb, 0x1e, 0x86, 0x20, 0xa2, 0xa3, 0xdd, 0x2a, 0xc9, 0x05, 0xea, 0x6e, 0x6d, 0x75, 0xc9, 0x31,
	0x3e, 0xf3, 0x00, 0x1c, 0x78, 0x02, 0x78, 0x0a, 0x1e, 0x82, 0x0b, 0x07, 0x22, 0xb8, 0xf0, 0x00,
	0x1c, 0xb9, 0x71, 0x24, 0xea, 0xa7, 0x5b, 0xdd, 0x1a, 0x8d, 0xc7, 0x17, 0x6e, 0x55, 0xdf, 0x97,
	0x95, 0x59, 0x95, 0x99, 0x9d, 0x55, 0xd9, 0xd0, 0x98, 0xb9, 0xcc, 0x9d, 0xba, 0x77, 0x27, 0x4b,
	0x16, 0xf2, 0x10, 0x95, 0x66, 0x6c, 0xca, 0x96, 0x9e, 0xf5, 0x5f, 0x03, 0x0e, 0x3b, 0x8b, 0x30,
	0x22, 0x98, 0x78, 0xa1, 0xef, 0x93, 0x60, 0xea, 0x72, 0x1a, 0x06, 0x98, 0x7c, 0xb7, 0x22, 0x11,
	0x47, 0x3f, 0x82, 0x5d, 0x9f, 0x06, 0xd4, 0x5f, 0xf9, 0x8e, 0x1f, 0x06, 0x94, 0x87, 0x8c, 0x4c,
	0x5b, 0xc6, 0x91, 0x71, 0x9c, 0xc7, 0xa6, 0x26, 0x06, 0x31, 0x8e, 0xda, 0x50, 0xf2, 0x09, 0x67,
	0xd4, 0x6b, 0xe5, 0x8e, 0x8c, 0xe3, 0xe6, 0xd9, 0x17, 0x27, 0xca, 0xc8, 0xc9, 0x87, 0x0d, 0x9c,
	0x0c, 0xe4, 0x02, 0xac, 0x17, 0x5a, 0xbf, 0x83, 0x92, 0x42, 0x50, 0x0d, 0xca, 0x97, 0xc3, 0x5f,
	0x0d, 0x47, 0x6f, 0x86, 0xe6, 0xf7, 0x10, 0x40, 0xe9, 0x72, 0x3c, 0xe9, 0x0d, 0x6c, 0xd3, 0x10,
	0x04, 0xb6, 0xaf, 0xec, 0xe1, 0xa5, 0x6d, 0xe6, 0xd0, 0x1e, 0xec, 0xf4, 0x86, 0x9d, 0xd1, 0xa0,
	0x37, 0x7c, 0xed, 0x5c, 0x8d, 0xfa, 0x97, 0x03, 0xdb, 0xcc, 0x0b, 0x70, 0x74, 0x39, 0x79, 0x3d,
	0x4a, 0x81, 0x05, 0x64, 0x42, 0x7d, 0x32, 0x9a, 0xb4, 0xfb, 0x31, 0x52, 0xb4, 0xfe, 0x64, 0xc0,
	0xd3, 0xd1, 0x8a, 0x2f, 0x28, 0x61, 0xd9, 0xbd, 0x45, 0xf1, 0xe9, 0x3b, 0x50, 0x63, 0xc4, 0x73,
	0x98, 0x9a, 0xca, 0x73, 0xd7, 0xce, 0xac, 0x8f, 0x9f, 0x0a, 0x03, 0x23, 0x5e, 0xac, 0xe4, 0x4b,
	0x40, 0xa1, 0xb2, 0xe2, 0xf8, 0xab, 0x05, 0xa7, 0x4b, 0x31, 0x94, 0x1e, 0xca, 0xe1, 0x5d, 0xcd,
	0x0c, 0x12, 0xc2, 0xfa, 0xa3, 0x01, 0xcf, 0x26, 0x37, 0x8c, 0x44, 0x37, 0xe1, 0x62, 0xfa, 0xff,
	0xdc, 0xd7, 0x0b, 0xd8, 0xe1, 0xb1, 0x1d, 0xe7, 0xd6, 0x5d, 0xac, 0x88, 0xde, 0x54, 0x33, 0x81,
	0xaf, 0x04, 0x6a, 0xfd, 0xd5, 0x80, 0x27, 0x5b, 0x74, 0x46, 0x98, 0x44, 0xcb, 0x30, 0x88, 0x08,
	0x7a, 0x0e, 0x4d, 0x1e, 0x72, 0x77, 0xe1, 0x78, 0x37, 0x6e, 0x10, 0x90, 0x45, 0x24, 0x77, 0x54,
	0xc4, 0x0d, 0x89, 0x76, 0x34, 0x88, 0x4e, 0x61, 0xcf, 0x0b, 0x83, 0x88, 0x4e, 0x09, 0x23, 0xd3,
	0xb5, 0x6c, 0x4e, 0xca, 0xa2, 0x35, 0x95, 0x2c, 0xf8, 0x1a, 0x76, 0x58, 0xd6, 0x64, 0x2b, 0x7f,
	0x94, 0x3f, 0xae, 0x9d, 0x1d, 0xc4, 0x47, 0xdd, 0x38, 0xe5, 0xa6, 0xb8, 0x15, 0x40, 0x33, 0x2b,
	0x82, 0x9e, 0x02, 0x08, 0xcb, 0xce, 0x32, 0xa4, 0x81, 0xf2, 0x5c, 0x15, 0x57, 0x05, 0x32, 0x16,
	0x00, 0xda, 0x87, 0x62, 0xda, 0x15, 0x6a, 0x22, 0x5c, 0x95, 0x68, 0x76, 0x3c, 0xe1, 0x8a, 0x56,
	0xfe, 0xc8, 0x38, 0xae, 0xe0, 0x66, 0x02, 0x4b, 0x07, 0x59, 0xdf, 0xc1, 0x3e, 0x26, 0xb7, 0x24,
	0x58, 0x11, 0x4c, 0x96, 0x21, 0xe3, 0xb1, 0xaf, 0x9f, 0x41, 0x6d, 0x6d, 0x55, 0xb8, 0x27, 0x7f,
	0x5c, 0xc5, 0x90, 0x98, 0x8d, 0xc4, 0xb6, 0x22, 0xee, 0x32, 0xee, 0x70, 0xea, 0x2b, 0xe3, 0x05,
	0x5c, 0x95, 0xc8, 0x84, 0xfa, 0x04, 0x7d, 0x0a, 0x15, 0x61, 0x5a, 0x92, 0x79, 0x49, 0x96, 0x49,
	0x30, 0x15, 0x94, 0x75, 0x0e, 0x8f, 0x36, 0x4c, 0xea, 0xa8, 0x9c, 0x42, 0x99, 0x49, 0x44, 0xd9,
	0xab, 0x9d, 0x3d, 0x5a, 0x7b, 0x2d, 0x2d, 0x1f, 0x4b, 0x59, 0xff, 0x30, 0xa0, 0x91, 0xa1, 0x64,
	0x60, 0x5d, 0x36, 0x27, 0x3c, 0x8e, 0x96, 0x76, 0x58, 0x43, 0xa1, 0x3a, 0x50, 0xa8, 0x07, 0xf5,
	0xa5, 0x4b, 0x99, 0x13, 0x9b, 0xcb, 0x49, 0x73, 0x3f, 0xdc, 0x6a, 0xee, 0x64, 0xec, 0x52, 0xa6,
	0x86, 0x91, 0x1d, 0x70, 0x76, 0x87, 0x6b, 0xcb, 0x35, 0x72, 0x88, 0xc1, 0xdc, 0x14, 0x40, 0x26,
	0xe4, 0x7f, 0x4f, 0xee, 0xb4, 0x69, 0x31, 0x44, 0xc7, 0xe9, 0x28, 0xd5, 0xce, 0x50, 0x6c, 0x69,
	0xbd, 0x54, 0x47, 0xee, 0x97, 0xb9, 0x9f, 0x1b, 0xd6, 0xdf, 0x0c, 0x80, 0x35, 0x83, 0xbe, 0x82,
	0x7d, 0xd7, 0x0f, 0x57, 0x01, 0x77, 0xc2, 0x15, 0x9f, 0x87, 0x34, 0x98, 0x3b, 0x7e, 0xe4, 0x72,
	0x5d, 0xd5, 0x90, 0xe2, 0x46, 0x9a, 0x1a, 0x44, 0x2e, 0x47, 0x3f, 0x06, 0x34, 0x23, 0x24, 0xda,
	0x90, 0xcf, 0xa9, 0x2a, 0x28, 0x98, 0x8c, 0xf4, 0x5a, 0x3f, 0x0d, 0xbc, 0xd0, 0x4f, 0xe4, 0xf3,
	0x69, 0xfd, 0x3d, 0x4d, 0x65, 0xf4, 0x67, 0xe5, 0x0b, 0x6b, 0xfd, 0x69, 0x69, 0xab, 0x05, 0x07,
	0xda, 0xf1, 0xbd, 0x20, 0xa2, 0xf3, 0x1b, 0x1e, 0x97, 0x05, 0xeb, 0xb7, 0xf0, 0xc9, 0x7b, 0x8c,
	0x4e, 0x86, 0x36, 0x98, 0x3a, 0x84, 0x0e, 0xd5, 0x9c, 0xce, 0x8a, 0xe4, 0x5b, 0xca, 0x2e, 0xc5,
	0x3b, 0x5e, 0x56, 0x95, 0xf5, 0xf7, 0x1c, 0x34, 0xb3, 0x32, 0x1f, 0xfb, 0x98, 0xc4, 0xe5, 0x11,
	0x5f, 0x0e, 0x4e, 0x44, 0xbc, 0x30, 0x98, 0x46, 0x3a, 0xb7, 0xcd, 0x84, 0xb8, 0x50, 0xb8, 0xc8,
	0xb5, 0xd5, 0x52, 0x24, 0x78, 0x22, 0xa9, 0x12, 0xbd, 0xa1, 0xd0, 0x58, 0xec, 0x2b, 0xd8, 0xbf,
	0x0d, 0x17, 0x2b, 0x9f, 0x6c, 0xf5, 0x16, 0x52, 0x5c, 0xc6, 0xbb, 0xeb, 0x15, 0xd9, 0xf8, 0x15,
	0xd3, 0x2b, 0x32, 0x11, 0x3c, 0x06, 0xe9, 0x75, 0x87, 0xb8, 0x2c, 0x20, 0x53, 0x25, 0x5d, 0x92,
	0xd2, 0x4d, 0x81, 0xdb, 0x12, 0x96, 0x92, 0x9f, 0x43, 0xc3, 0x0b, 0x83, 0x19, 0x65, 0xbe, 0xae,
	0x4f, 0xe5, 0x23, 0xe3, 0xb8, 0x81, 0xb3, 0x20, 0x6a, 0x41, 0x79, 0xc9, 0xe8, 0xad, 0xcb, 0x49,
	0xab, 0x22, 0xcb, 0x46, 0x3c, 0xb5, 0xde, 0xc1, 0x9e, 0xfd, 0x4e, 0x38, 0x6c, 0x4e, 0xb0, 0xcb,
	0x49, 0x5c, 0x2e, 0x3e, 0x03, 0x10, 0x67, 0x8e, 0xb8, 0xeb, 0x2f, 0x55, 0xcd, 0x2b, 0xe0, 0x14,
	0x82, 0x7e, 0x06, 0xb5, 0x39, 0x73, 0x83, 0xd5, 0xc2, 0x65, 0x94, 0xdf, 0xc9, 0xb3, 0x37, 0xcf,
	0xf6, 0xe2, 0x40, 0xbe, 0x5e, 0x53, 0x38, 0x2d, 0xf7, 0x6d, 0xa1, 0x62, 0x98, 0xb9, 0x6f, 0x0b,
	0x95, 0x9c, 0x99, 0xb7, 0xce, 0x61, 0x3f, 0x6b, 0x59, 0x27, 0xca, 0x4b, 0x28, 0x32, 0x97, 0x93,
	0xf8, 0x23, 0xde, 0x8f, 0x95, 0x66, 0x84, 0x95, 0x88, 0xd2, 0x67, 0x0d, 0xa0, 0xfe, 0x8a, 0x72,
	0x2f, 0xa4, 0xc1, 0x98, 0x51, 0x8f, 0x88, 0x12, 0xba, 0x14, 0x03, 0x9d, 0x0f, 0x6a, 0x22, 0x4a,
	0xa8, 0x1c, 0x38, 0xc9, 0x31, 0x74, 0x26, 0x34, 0x25, 0x3c, 0x89, 0x51, 0xcb, 0x81, 0x7a, 0xda,
	0x16, 0x7a, 0x02, 0xd5, 0xf5, 0x12, 0x43, 0x15, 0xc6, 0x04, 0x40, 0x3f, 0x81, 0xea, 0x35, 0xf7,
	0x1c, 0x65, 0x50, 0x55, 0x83, 0x64, 0xcb, 0xe9, 0x5d, 0xe1, 0xca, 0x35, 0xf7, 0xe4, 0xc8, 0xfa,
	0x8f, 0x01, 0xe6, 0x30, 0x9c, 0x92, 0xf6, 0x6a, 0x4a, 0x93, 0x02, 0x9d, 0xad, 0xbf, 0xc6, 0x7d,
	0xf5, 0x37, 0x97, 0xa9, 0xbf, 0xe8, 0xfb, 0x50, 0x9f, 0xd2, 0xc8, 0xbd, 0x5e, 0x10, 0x67, 0x46,
	0x75, 0x22, 0x56, 0x70, 0x4d, 0x63, 0x5d, 0xea, 0xf2, 0xcd, 0x70, 0x15, 0x1f, 0x16, 0x2e, 0xd4,
	0x81, 0x5d, 0x6f, 0x15, 0xf1, 0xd0, 0x77, 0x3c, 0x97, 0x93, 0x79, 0xc8, 0x28, 0x89, 0x5a, 0xa5,
	0x8d, 0x8f, 0x56, 0x0a, 0x74, 0x14, 0x7f, 0x87, 0x4d, 0x2f, 0x3d, 0xa7, 0x32, 0x46, 0x79, 0xb3,
	0x60, 0xfd, 0xc1, 0x80, 0x66, 0x56, 0x14, 0x21, 0x28, 0x04, 0xae, 0x1f, 0x47, 0x49, 0x8e, 0xc5,
	0x31, 0xc3, 0x40, 0xd4, 0x7a, 0x1a, 0xc8, 0x63, 0x56, 0x70, 0x39, 0x0c, 0x3a, 0x62, 0x8a, 0x1e,
	0x43, 0x35, 0x9c, 0xcd, 0x34, 0xa7, 0x2e, 0xbf, 0x4a, 0x38, 0x9b, 0x29, 0xf2, 0x39, 0x34, 0x17,
	0xee, 0x35, 0x59, 0x38, 0x4b, 0x97, 0x73, 0xc2, 0x82, 0xa8, 0x55, 0x94, 0x37, 0x5c, 0x43, 0xa2,
	0x63, 0x0d, 0x5a, 0xff, 0xce, 0x41, 0x4d, 0x15, 0x61, 0x55, 0xd8, 0xef, 0x0f, 0xed, 0x3d, 0x9b,
	0x39, 0x80, 0x92, 0x2a, 0xa3, 0xba, 0x46, 0xe8, 0x99, 0xc0, 0x3d, 0x46, 0xa6, 0x34, 0x8e, 0x82,
	0x9e, 0x89, 0x94, 0x74, 0xa3, 0x88, 0xa8, 0x6f, 0xbe, 0x8a, 0xd5, 0x04, 0x3d, 0x87, 0x02, 0xbf,
	0x5b, 0x12, 0xf9, 0x69, 0x37, 0xcf, 0x76, 0x93, 0x4c, 0x17, 0x7b, 0x9b, 0xdc, 0x2d, 0x09, 0x96,
	0xb4, 0xc8, 0xdc, 0x6c, 0x18, 0xee, 0x5a, 0x75, 0xa9, 0xa6, 0xe9, 0xbd, 0xe7, 0x51, 0xfe, 0x8e,
	0x4e, 0x65, 0x0d, 0xa8, 0x62, 0x39, 0x16, 0x98, 0xcc, 0x8a, 0x8a, 0xc2, 0xc4, 0x58, 0x1c, 0x9b,
	0x91, 0x19, 0x61, 0x24, 0xf0, 0x48, 0xab, 0xaa, 0x8a, 0x66, 0x02, 0xc8, 0xb8, 0x84, 0x9c, 0xb4,
	0x40, 0xc7, 0x25, 0xe4, 0x24, 0x9b, 0xe5, 0xb5, 0x07, 0x65, 0xf9, 0x2b, 0xd8, 0x4d, 0x25, 0xb9,
	0xfe, 0xb8, 0xbf, 0xdc, 0x7c, 0x12, 0xec, 0xad, 0xef, 0xe8, 0x24, 0x2c, 0xeb, 0x07, 0xc1, 0x2f,
	0x00, 0xe9, 0x77, 0x5f, 0xfa, 0x2d, 0xf3, 0x03, 0x68, 0xc4, 0x57, 0x49, 0xba, 0xee, 0xd7, 0x35,
	0x28, 0x4b, 0xbf, 0xf5, 0x2f, 0x03, 0xf6, 0x32, 0x6b, 0xf5, 0x0e, 0x1e, 0xb2, 0x58, 0xdc, 0x1b,
	0xeb, 0xcb, 0x8a, 0x72, 0xea, 0xf2, 0x90, 0xe9, 0x14, 0x30, 0x93, 0x5b, 0x49, 0xe3, 0xf2, 0x0e,
	0x12, 0x86, 0x1c, 0x19, 0xcb, 0xbc, 0xbe, 0x83, 0x04, 0x22, 0x62, 0x98, 0xa2, 0x45, 0x68, 0x0a,
	0x69, 0x5a, 0xc4, 0x47, 0x24, 0xd9, 0x92, 0x04, 0xce, 0x8c, 0x10, 0x9d, 0x1c, 0x65, 0x31, 0xef,
	0x12, 0x22, 0x32, 0x5e, 0xad, 0x14, 0x5c, 0x49, 0x72, 0x15, 0x09, 0x74, 0x09, 0x79, 0xf9, 0x67,
	0x03, 0x6a, 0xa9, 0x0f, 0x17, 0x7d, 0x02, 0x7b, 0xba, 0x5b, 0x71, 0x5e, 0xe3, 0xf6, 0xf0, 0xb2,
	0xdf, 0xc6, 0xbd, 0xc9, 0x5b, 0xd5, 0xb9, 0x0c, 0x7a, 0xc3, 0xcb, 0x89, 0xe8, 0x5c, 0x4c, 0xa8,
	0x77, 0x7b, 0x57, 0xb6, 0xa3, 0x80, 0x0b, 0xd5, 0xbe, 0x74, 0x7b, 0xdd, 0x89, 0x6d, 0x0f, 0x13,
	0x30, 0x8f, 0x10, 0x34, 0x27, 0xe7, 0x3d, 0x3c, 0x79, 0x9b, 0x60, 0x05, 0x54, 0x81, 0xc2, 0xf9,
	0xe8, 0x12, 0x9b, 0x45, 0xd4, 0x80, 0xea, 0x45, 0xef, 0xd7, 0x8e, 0x98, 0x5d, 0x98, 0x25, 0xd9,
	0xd6, 0xbc, 0xb1, 0xfb, 0x57, 0xb6, 0x46, 0xca, 0xa8, 0x0c, 0xf9, 0x6f, 0xda, 0x6f, 0xcd, 0xca,
	0xcb, 0xbf, 0xe4, 0xa0, 0x9a, 0x24, 0x73, 0xb6, 0x9f, 0x3a, 0x00, 0xd4, 0x1f, 0x75, 0xda, 0x7d,
	0xa7, 0x73, 0xde, 0x1e, 0x0e, 0xed, 0xbe, 0x33, 0x1a, 0xdb, 0x43, 0xd3, 0x10, 0xc7, 0xc0, 0xf6,
	0x60, 0x34, 0xb1, 0xb3, 0x44, 0x0e, 0xed, 0x83, 0x99, 0x46, 0x9c, 0xae, 0x2d, 0x1a, 0xad, 0x5d,
	0x68, 0xc4, 0x68, 0xa7, 0x3f, 0xba, 0x10, 0x6d, 0x96, 0xec, 0xce, 0x3a, 0x76, 0x6f, 0x3c, 0x31,
	0x8b, 0x62, 0x32, 0x6e, 0xbf, 0x1d, 0xd8, 0xc3, 0x89, 0x59, 0x12, 0xfb, 0x12, 0xab, 0xca, 0x52,
	0x57, 0x0f, 0x77, 0x84, 0x8f, 0x9c, 0x58, 0xb6, 0x22, 0x64, 0xbb, 0x23, 0xfc, 0xa6, 0x8d, 0xbf,
	0x31, 0xab, 0x68, 0x07, 0x6a, 0x7a, 0x22, 0x2d, 0x41, 0x66, 0x4d, 0xac, 0xb2, 0x26, 0x0e, 0x9f,
	0xa0, 0x42, 0xae, 0x8e, 0xaa, 0x50, 0xbc, 0x78, 0x63, 0xdb, 0x63, 0xb3, 0x21, 0x1d, 0x25, 0x86,
	0x92, 0x69, 0xa2, 0x47, 0xb0, 0x9b, 0xd9, 0xab, 0x84, 0x77, 0xce, 0xfe, 0x59, 0x80, 0x46, 0x57,
	0x75, 0xc6, 0x17, 0x84, 0xdd, 0x12, 0x86, 0x08, 0x1c, 0x6c, 0xef, 0x0a, 0xd1, 0xf3, 0xf8, 0x6b,
	0xb9, 0xb7, 0x6b, 0x3c, 0xfc, 0xfc, 0x9e, 0x46, 0x6c, 0xfd, 0x22, 0xa3, 0xd0, 0xfa, 0x50, 0x9b,
	0x87, 0x5e, 0xc4, 0x1a, 0x3e, 0xd2, 0x08, 0x3e, 0xd0, 0x54, 0x7f, 0xf3, 0x5d, 0xff, 0x64, 0x7b,
	0x27, 0xa0, 0x95, 0x3e, 0xfd, 0x00, 0xab, 0xb5, 0x61, 0xd8, 0xd9, 0x78, 0x65, 0xa2, 0xcf, 0xb6,
	0xbf, 0x21, 0x93, 0x6d, 0x3e, 0xfb, 0x20, 0xaf, 0x75, 0xf6, 0x36, 0x2e, 0xfd, 0xc7, 0x5b, 0x9f,
	0x1d, 0x5a, 0xdb, 0x93, 0xed, 0xa4, 0x56, 0xf5, 0x35, 0x54, 0x93, 0xc2, 0x87, 0x5a, 0xb1, 0xe8,
	0xe6, 0x85, 0x7f, 0xf8, 0xe9, 0x16, 0x46, 0x6b, 0xe8, 0x42, 0x2d, 0x55, 0xba, 0xd0, 0xe1, 0x86,
	0x8f, 0xd3, 0xae, 0x7a, 0xbc, 0x95, 0x53, 0x7a, 0x5e, 0x7d, 0xf1, 0x9b, 0x17, 0x73, 0xca, 0x6f,
	0x56, 0xd7, 0x27, 0x5e, 0xe8, 0x9f, 0x2e, 0xc4, 0x89, 0x03, 0x1a, 0xcc, 0x17, 0xee, 0x75, 0x74,
	0xaa, 0x7f, 0xc6, 0x9c, 0xaa, 0xe5, 0xd7, 0x25, 0xf9, 0x53, 0xe6, 0xa7, 0xff, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x59, 0x74, 0xca, 0x6f, 0xa5, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaradayServerClient is the client API for FaradayServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaradayServerClient interface {
	//* frcli: `outliers`
	//Get close recommendations for currently open channels based on whether it is
	//an outlier.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/outliers/REVENUE?rec_request.minimum_monitored=123
	OutlierRecommendations(ctx context.Context, in *OutlierRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error)
	//* frcli: `threshold`
	//Get close recommendations for currently open channels based whether they are
	//below a set threshold.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/threshold/UPTIME?rec_request.minimum_monitored=123
	ThresholdRecommendations(ctx context.Context, in *ThresholdRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error)
	//* frcli: `revenue`
	//Get a pairwise revenue report for a channel.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/revenue
	RevenueReport(ctx context.Context, in *RevenueReportRequest, opts ...grpc.CallOption) (*RevenueReportResponse, error)
	//* frcli: `insights`
	//List currently open channel with routing and uptime information.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/insights
	ChannelInsights(ctx context.Context, in *ChannelInsightsRequest, opts ...grpc.CallOption) (*ChannelInsightsResponse, error)
	//* frcli:
	//Get fiat prices for btc.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/exchangerate
	ExchangeRate(ctx context.Context, in *ExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error)
	//*
	//Get a report of your node's activity over a period.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/nodeaudit
	NodeAudit(ctx context.Context, in *NodeAuditRequest, opts ...grpc.CallOption) (*NodeAuditResponse, error)
	//*
	//Get a channel close report for a specific channel.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/closereport
	CloseReport(ctx context.Context, in *CloseReportRequest, opts ...grpc.CallOption) (*CloseReportResponse, error)
}

type faradayServerClient struct {
	cc *grpc.ClientConn
}

func NewFaradayServerClient(cc *grpc.ClientConn) FaradayServerClient {
	return &faradayServerClient{cc}
}

func (c *faradayServerClient) OutlierRecommendations(ctx context.Context, in *OutlierRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error) {
	out := new(CloseRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/OutlierRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) ThresholdRecommendations(ctx context.Context, in *ThresholdRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error) {
	out := new(CloseRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/ThresholdRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) RevenueReport(ctx context.Context, in *RevenueReportRequest, opts ...grpc.CallOption) (*RevenueReportResponse, error) {
	out := new(RevenueReportResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/RevenueReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) ChannelInsights(ctx context.Context, in *ChannelInsightsRequest, opts ...grpc.CallOption) (*ChannelInsightsResponse, error) {
	out := new(ChannelInsightsResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/ChannelInsights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) ExchangeRate(ctx context.Context, in *ExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error) {
	out := new(ExchangeRateResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/ExchangeRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) NodeAudit(ctx context.Context, in *NodeAuditRequest, opts ...grpc.CallOption) (*NodeAuditResponse, error) {
	out := new(NodeAuditResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/NodeAudit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) CloseReport(ctx context.Context, in *CloseReportRequest, opts ...grpc.CallOption) (*CloseReportResponse, error) {
	out := new(CloseReportResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/CloseReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaradayServerServer is the server API for FaradayServer service.
type FaradayServerServer interface {
	//* frcli: `outliers`
	//Get close recommendations for currently open channels based on whether it is
	//an outlier.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/outliers/REVENUE?rec_request.minimum_monitored=123
	OutlierRecommendations(context.Context, *OutlierRecommendationsRequest) (*CloseRecommendationsResponse, error)
	//* frcli: `threshold`
	//Get close recommendations for currently open channels based whether they are
	//below a set threshold.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/threshold/UPTIME?rec_request.minimum_monitored=123
	ThresholdRecommendations(context.Context, *ThresholdRecommendationsRequest) (*CloseRecommendationsResponse, error)
	//* frcli: `revenue`
	//Get a pairwise revenue report for a channel.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/revenue
	RevenueReport(context.Context, *RevenueReportRequest) (*RevenueReportResponse, error)
	//* frcli: `insights`
	//List currently open channel with routing and uptime information.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/insights
	ChannelInsights(context.Context, *ChannelInsightsRequest) (*ChannelInsightsResponse, error)
	//* frcli:
	//Get fiat prices for btc.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/exchangerate
	ExchangeRate(context.Context, *ExchangeRateRequest) (*ExchangeRateResponse, error)
	//*
	//Get a report of your node's activity over a period.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/nodeaudit
	NodeAudit(context.Context, *NodeAuditRequest) (*NodeAuditResponse, error)
	//*
	//Get a channel close report for a specific channel.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/closereport
	CloseReport(context.Context, *CloseReportRequest) (*CloseReportResponse, error)
}

// UnimplementedFaradayServerServer can be embedded to have forward compatible implementations.
type UnimplementedFaradayServerServer struct {
}

func (*UnimplementedFaradayServerServer) OutlierRecommendations(ctx context.Context, req *OutlierRecommendationsRequest) (*CloseRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OutlierRecommendations not implemented")
}
func (*UnimplementedFaradayServerServer) ThresholdRecommendations(ctx context.Context, req *ThresholdRecommendationsRequest) (*CloseRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThresholdRecommendations not implemented")
}
func (*UnimplementedFaradayServerServer) RevenueReport(ctx context.Context, req *RevenueReportRequest) (*RevenueReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevenueReport not implemented")
}
func (*UnimplementedFaradayServerServer) ChannelInsights(ctx context.Context, req *ChannelInsightsRequest) (*ChannelInsightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChannelInsights not implemented")
}
func (*UnimplementedFaradayServerServer) ExchangeRate(ctx context.Context, req *ExchangeRateRequest) (*ExchangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeRate not implemented")
}
func (*UnimplementedFaradayServerServer) NodeAudit(ctx context.Context, req *NodeAuditRequest) (*NodeAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeAudit not implemented")
}
func (*UnimplementedFaradayServerServer) CloseReport(ctx context.Context, req *CloseReportRequest) (*CloseReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseReport not implemented")
}

func RegisterFaradayServerServer(s *grpc.Server, srv FaradayServerServer) {
	s.RegisterService(&_FaradayServer_serviceDesc, srv)
}

func _FaradayServer_OutlierRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutlierRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).OutlierRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/OutlierRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).OutlierRecommendations(ctx, req.(*OutlierRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_ThresholdRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThresholdRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).ThresholdRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/ThresholdRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).ThresholdRecommendations(ctx, req.(*ThresholdRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_RevenueReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevenueReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).RevenueReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/RevenueReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).RevenueReport(ctx, req.(*RevenueReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_ChannelInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).ChannelInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/ChannelInsights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).ChannelInsights(ctx, req.(*ChannelInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_ExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).ExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/ExchangeRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).ExchangeRate(ctx, req.(*ExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_NodeAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).NodeAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/NodeAudit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).NodeAudit(ctx, req.(*NodeAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_CloseReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).CloseReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/CloseReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).CloseReport(ctx, req.(*CloseReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FaradayServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frdrpc.FaradayServer",
	HandlerType: (*FaradayServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OutlierRecommendations",
			Handler:    _FaradayServer_OutlierRecommendations_Handler,
		},
		{
			MethodName: "ThresholdRecommendations",
			Handler:    _FaradayServer_ThresholdRecommendations_Handler,
		},
		{
			MethodName: "RevenueReport",
			Handler:    _FaradayServer_RevenueReport_Handler,
		},
		{
			MethodName: "ChannelInsights",
			Handler:    _FaradayServer_ChannelInsights_Handler,
		},
		{
			MethodName: "ExchangeRate",
			Handler:    _FaradayServer_ExchangeRate_Handler,
		},
		{
			MethodName: "NodeAudit",
			Handler:    _FaradayServer_NodeAudit_Handler,
		},
		{
			MethodName: "CloseReport",
			Handler:    _FaradayServer_CloseReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faraday.proto",
}
