// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package frdrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CloseRecommendationRequest_Metric int32

const (
	CloseRecommendationRequest_UNKNOWN         CloseRecommendationRequest_Metric = 0
	CloseRecommendationRequest_UPTIME          CloseRecommendationRequest_Metric = 1
	CloseRecommendationRequest_REVENUE         CloseRecommendationRequest_Metric = 2
	CloseRecommendationRequest_INCOMING_VOLUME CloseRecommendationRequest_Metric = 3
	CloseRecommendationRequest_OUTGOING_VOLUME CloseRecommendationRequest_Metric = 4
	CloseRecommendationRequest_TOTAL_VOLUME    CloseRecommendationRequest_Metric = 5
)

var CloseRecommendationRequest_Metric_name = map[int32]string{
	0: "UNKNOWN",
	1: "UPTIME",
	2: "REVENUE",
	3: "INCOMING_VOLUME",
	4: "OUTGOING_VOLUME",
	5: "TOTAL_VOLUME",
}

var CloseRecommendationRequest_Metric_value = map[string]int32{
	"UNKNOWN":         0,
	"UPTIME":          1,
	"REVENUE":         2,
	"INCOMING_VOLUME": 3,
	"OUTGOING_VOLUME": 4,
	"TOTAL_VOLUME":    5,
}

func (x CloseRecommendationRequest_Metric) String() string {
	return proto.EnumName(CloseRecommendationRequest_Metric_name, int32(x))
}

func (CloseRecommendationRequest_Metric) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0, 0}
}

// Granularity describes the aggregation level at which the Bitcoin price
// is provided.
type FiatEstimateRequest_Granularity int32

const (
	FiatEstimateRequest_UNKNOWN         FiatEstimateRequest_Granularity = 0
	FiatEstimateRequest_MINUTE          FiatEstimateRequest_Granularity = 1
	FiatEstimateRequest_FIVE_MINUTES    FiatEstimateRequest_Granularity = 2
	FiatEstimateRequest_FIFTEEN_MINUTES FiatEstimateRequest_Granularity = 3
	FiatEstimateRequest_THIRTY_MINUTES  FiatEstimateRequest_Granularity = 4
	FiatEstimateRequest_HOUR            FiatEstimateRequest_Granularity = 5
	FiatEstimateRequest_SIX_HOURS       FiatEstimateRequest_Granularity = 6
	FiatEstimateRequest_TWELVE_HOURS    FiatEstimateRequest_Granularity = 7
	FiatEstimateRequest_DAY             FiatEstimateRequest_Granularity = 8
)

var FiatEstimateRequest_Granularity_name = map[int32]string{
	0: "UNKNOWN",
	1: "MINUTE",
	2: "FIVE_MINUTES",
	3: "FIFTEEN_MINUTES",
	4: "THIRTY_MINUTES",
	5: "HOUR",
	6: "SIX_HOURS",
	7: "TWELVE_HOURS",
	8: "DAY",
}

var FiatEstimateRequest_Granularity_value = map[string]int32{
	"UNKNOWN":         0,
	"MINUTE":          1,
	"FIVE_MINUTES":    2,
	"FIFTEEN_MINUTES": 3,
	"THIRTY_MINUTES":  4,
	"HOUR":            5,
	"SIX_HOURS":       6,
	"TWELVE_HOURS":    7,
	"DAY":             8,
}

func (x FiatEstimateRequest_Granularity) String() string {
	return proto.EnumName(FiatEstimateRequest_Granularity_name, int32(x))
}

func (FiatEstimateRequest_Granularity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12, 0}
}

type CloseRecommendationRequest struct {
	//
	//The minimum amount of time in seconds that a channel should have been
	//monitored by lnd to be eligible for close. This value is in place to
	//protect against closing of newer channels.
	MinimumMonitored int64 `protobuf:"varint,1,opt,name=minimum_monitored,json=minimumMonitored,proto3" json:"minimum_monitored,omitempty"`
	//
	//The data point base close recommendations on. Available options are:
	//Uptime: ratio of channel peer's uptime to the period they have been
	//monitored to.
	//Revenue: the revenue that the channel has produced per block that its
	//funding transaction has been confirmed for.
	Metric               CloseRecommendationRequest_Metric `protobuf:"varint,2,opt,name=metric,proto3,enum=frdrpc.CloseRecommendationRequest_Metric" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CloseRecommendationRequest) Reset()         { *m = CloseRecommendationRequest{} }
func (m *CloseRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRecommendationRequest) ProtoMessage()    {}
func (*CloseRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *CloseRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRecommendationRequest.Unmarshal(m, b)
}
func (m *CloseRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *CloseRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRecommendationRequest.Merge(m, src)
}
func (m *CloseRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRecommendationRequest.Size(m)
}
func (m *CloseRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRecommendationRequest proto.InternalMessageInfo

func (m *CloseRecommendationRequest) GetMinimumMonitored() int64 {
	if m != nil {
		return m.MinimumMonitored
	}
	return 0
}

func (m *CloseRecommendationRequest) GetMetric() CloseRecommendationRequest_Metric {
	if m != nil {
		return m.Metric
	}
	return CloseRecommendationRequest_UNKNOWN
}

type OutlierRecommendationsRequest struct {
	//
	//The parameters that are common to all close recommendations.
	RecRequest *CloseRecommendationRequest `protobuf:"bytes,1,opt,name=rec_request,json=recRequest,proto3" json:"rec_request,omitempty"`
	//
	//The number of inter-quartile ranges a value needs to be beneath the lower
	//quartile/ above the upper quartile to be considered a lower/upper outlier.
	//Lower values will be more aggressive in recommending channel closes, and
	//upper values will be more conservative. Recommended values are 1.5 for
	//aggressive recommendations and 3 for conservative recommendations.
	OutlierMultiplier    float32  `protobuf:"fixed32,2,opt,name=outlier_multiplier,json=outlierMultiplier,proto3" json:"outlier_multiplier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutlierRecommendationsRequest) Reset()         { *m = OutlierRecommendationsRequest{} }
func (m *OutlierRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*OutlierRecommendationsRequest) ProtoMessage()    {}
func (*OutlierRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *OutlierRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutlierRecommendationsRequest.Unmarshal(m, b)
}
func (m *OutlierRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutlierRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *OutlierRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutlierRecommendationsRequest.Merge(m, src)
}
func (m *OutlierRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_OutlierRecommendationsRequest.Size(m)
}
func (m *OutlierRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutlierRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutlierRecommendationsRequest proto.InternalMessageInfo

func (m *OutlierRecommendationsRequest) GetRecRequest() *CloseRecommendationRequest {
	if m != nil {
		return m.RecRequest
	}
	return nil
}

func (m *OutlierRecommendationsRequest) GetOutlierMultiplier() float32 {
	if m != nil {
		return m.OutlierMultiplier
	}
	return 0
}

type ThresholdRecommendationsRequest struct {
	//
	//The parameters that are common to all close recommendations.
	RecRequest *CloseRecommendationRequest `protobuf:"bytes,1,opt,name=rec_request,json=recRequest,proto3" json:"rec_request,omitempty"`
	//
	//The threshold that recommendations will be calculated based on.
	//For uptime: ratio of uptime to observed lifetime beneath which channels
	//will be recommended for closure.
	//
	//For revenue: revenue per block that capital has been committed to the
	//channel beneath which channels will be recommended for closure. This
	//value is provided per block so that channels that have been open for
	//different periods of time can be compared.
	//
	//For incoming volume: The incoming volume per block that capital has
	//been committed to the channel beneath which channels will be recommended
	//for closure. This value is provided per block so that channels that have
	//been open for different periods of time can be compared.
	//
	//For outgoing volume: The outgoing volume per block that capital has been
	//committed to the channel beneath which channels will be recommended for
	//closure. This value is provided per block so that channels that have been
	//open for different periods of time can be compared.
	//
	//For total volume: The total volume per block that capital has been
	//committed to the channel beneath which channels will be recommended for
	//closure. This value is provided per block so that channels that have been
	//open for different periods of time can be compared.
	ThresholdValue       float32  `protobuf:"fixed32,2,opt,name=threshold_value,json=thresholdValue,proto3" json:"threshold_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThresholdRecommendationsRequest) Reset()         { *m = ThresholdRecommendationsRequest{} }
func (m *ThresholdRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ThresholdRecommendationsRequest) ProtoMessage()    {}
func (*ThresholdRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *ThresholdRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Unmarshal(m, b)
}
func (m *ThresholdRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ThresholdRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdRecommendationsRequest.Merge(m, src)
}
func (m *ThresholdRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Size(m)
}
func (m *ThresholdRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdRecommendationsRequest proto.InternalMessageInfo

func (m *ThresholdRecommendationsRequest) GetRecRequest() *CloseRecommendationRequest {
	if m != nil {
		return m.RecRequest
	}
	return nil
}

func (m *ThresholdRecommendationsRequest) GetThresholdValue() float32 {
	if m != nil {
		return m.ThresholdValue
	}
	return 0
}

type CloseRecommendationsResponse struct {
	//
	//The total number of channels, before filtering out channels that are
	//not eligible for close recommendations.
	TotalChannels int32 `protobuf:"varint,1,opt,name=total_channels,json=totalChannels,proto3" json:"total_channels,omitempty"`
	//
	//The number of channels that were considered for close recommendations.
	ConsideredChannels int32 `protobuf:"varint,2,opt,name=considered_channels,json=consideredChannels,proto3" json:"considered_channels,omitempty"`
	//
	//A set of channel close recommendations. The absence of a channel in this
	//set implies that it was not considered for close because it did not meet
	//the criteria for close recommendations (it is private, or has not been
	//monitored for long enough).
	Recommendations      []*Recommendation `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CloseRecommendationsResponse) Reset()         { *m = CloseRecommendationsResponse{} }
func (m *CloseRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*CloseRecommendationsResponse) ProtoMessage()    {}
func (*CloseRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *CloseRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRecommendationsResponse.Unmarshal(m, b)
}
func (m *CloseRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *CloseRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRecommendationsResponse.Merge(m, src)
}
func (m *CloseRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_CloseRecommendationsResponse.Size(m)
}
func (m *CloseRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRecommendationsResponse proto.InternalMessageInfo

func (m *CloseRecommendationsResponse) GetTotalChannels() int32 {
	if m != nil {
		return m.TotalChannels
	}
	return 0
}

func (m *CloseRecommendationsResponse) GetConsideredChannels() int32 {
	if m != nil {
		return m.ConsideredChannels
	}
	return 0
}

func (m *CloseRecommendationsResponse) GetRecommendations() []*Recommendation {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

type Recommendation struct {
	//
	//The channel point [funding txid: outpoint] of the channel being considered
	//for close.
	ChanPoint string `protobuf:"bytes,1,opt,name=chan_point,json=chanPoint,proto3" json:"chan_point,omitempty"`
	// The value of the metric that close recommendations were based on.
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// A boolean indicating whether we recommend closing the channel.
	RecommendClose       bool     `protobuf:"varint,3,opt,name=recommend_close,json=recommendClose,proto3" json:"recommend_close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recommendation) Reset()         { *m = Recommendation{} }
func (m *Recommendation) String() string { return proto.CompactTextString(m) }
func (*Recommendation) ProtoMessage()    {}
func (*Recommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *Recommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation.Unmarshal(m, b)
}
func (m *Recommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation.Merge(m, src)
}
func (m *Recommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation.Size(m)
}
func (m *Recommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation proto.InternalMessageInfo

func (m *Recommendation) GetChanPoint() string {
	if m != nil {
		return m.ChanPoint
	}
	return ""
}

func (m *Recommendation) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Recommendation) GetRecommendClose() bool {
	if m != nil {
		return m.RecommendClose
	}
	return false
}

type RevenueReportRequest struct {
	//
	//The funding transaction outpoints for the channels to generate a revenue
	//report for. If this is empty, it will be generated for all open and closed
	//channels. Channel funding points should be expressed with the format
	//fundingTxID:outpoint.
	ChanPoints []string `protobuf:"bytes,1,rep,name=chan_points,json=chanPoints,proto3" json:"chan_points,omitempty"`
	//
	//Start time is beginning of the range over which the report will be
	//generated, expressed as unix epoch offset in seconds.
	StartTime uint64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	//
	//End time is end of the range over which the report will be
	//generated, expressed as unix epoch offset in seconds.
	EndTime              uint64   `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevenueReportRequest) Reset()         { *m = RevenueReportRequest{} }
func (m *RevenueReportRequest) String() string { return proto.CompactTextString(m) }
func (*RevenueReportRequest) ProtoMessage()    {}
func (*RevenueReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *RevenueReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReportRequest.Unmarshal(m, b)
}
func (m *RevenueReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReportRequest.Marshal(b, m, deterministic)
}
func (m *RevenueReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReportRequest.Merge(m, src)
}
func (m *RevenueReportRequest) XXX_Size() int {
	return xxx_messageInfo_RevenueReportRequest.Size(m)
}
func (m *RevenueReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReportRequest proto.InternalMessageInfo

func (m *RevenueReportRequest) GetChanPoints() []string {
	if m != nil {
		return m.ChanPoints
	}
	return nil
}

func (m *RevenueReportRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RevenueReportRequest) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type RevenueReportResponse struct {
	//
	//Reports is a set of pairwise revenue report generated for the channel(s)
	//over the period specified.
	Reports              []*RevenueReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RevenueReportResponse) Reset()         { *m = RevenueReportResponse{} }
func (m *RevenueReportResponse) String() string { return proto.CompactTextString(m) }
func (*RevenueReportResponse) ProtoMessage()    {}
func (*RevenueReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *RevenueReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReportResponse.Unmarshal(m, b)
}
func (m *RevenueReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReportResponse.Marshal(b, m, deterministic)
}
func (m *RevenueReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReportResponse.Merge(m, src)
}
func (m *RevenueReportResponse) XXX_Size() int {
	return xxx_messageInfo_RevenueReportResponse.Size(m)
}
func (m *RevenueReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReportResponse proto.InternalMessageInfo

func (m *RevenueReportResponse) GetReports() []*RevenueReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

type RevenueReport struct {
	//
	//Target channel is the channel that the report is generated for; incoming
	//fields in the report mean that this channel was the incoming channel,
	//and the pair as the outgoing, outgoing fields mean that this channel was
	//the outgoing channel and the peer was the incoming channel.
	TargetChannel string `protobuf:"bytes,1,opt,name=target_channel,json=targetChannel,proto3" json:"target_channel,omitempty"`
	//
	//Pair reports maps the channel point of a peer that we generated revenue
	//with to a report detailing the revenue.
	PairReports          map[string]*PairReport `protobuf:"bytes,2,rep,name=pair_reports,json=pairReports,proto3" json:"pair_reports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RevenueReport) Reset()         { *m = RevenueReport{} }
func (m *RevenueReport) String() string { return proto.CompactTextString(m) }
func (*RevenueReport) ProtoMessage()    {}
func (*RevenueReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *RevenueReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReport.Unmarshal(m, b)
}
func (m *RevenueReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReport.Marshal(b, m, deterministic)
}
func (m *RevenueReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReport.Merge(m, src)
}
func (m *RevenueReport) XXX_Size() int {
	return xxx_messageInfo_RevenueReport.Size(m)
}
func (m *RevenueReport) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReport.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReport proto.InternalMessageInfo

func (m *RevenueReport) GetTargetChannel() string {
	if m != nil {
		return m.TargetChannel
	}
	return ""
}

func (m *RevenueReport) GetPairReports() map[string]*PairReport {
	if m != nil {
		return m.PairReports
	}
	return nil
}

type PairReport struct {
	//
	//Amount outgoing msat is the amount in millisatoshis that arrived
	//on the pair channel to be forwarded onwards by our channel.
	AmountOutgoingMsat int64 `protobuf:"varint,1,opt,name=amount_outgoing_msat,json=amountOutgoingMsat,proto3" json:"amount_outgoing_msat,omitempty"`
	//
	//Fees outgoing is the amount of fees in millisatoshis that we
	//attribute to the channel for its role as the outgoing channel in
	//forwards.
	FeesOutgoingMsat int64 `protobuf:"varint,2,opt,name=fees_outgoing_msat,json=feesOutgoingMsat,proto3" json:"fees_outgoing_msat,omitempty"`
	//
	//Amount incoming msat is the amount in millisatoshis that arrived
	//on our channel to be forwarded onwards by the pair channel.
	AmountIncomingMsat int64 `protobuf:"varint,3,opt,name=amount_incoming_msat,json=amountIncomingMsat,proto3" json:"amount_incoming_msat,omitempty"`
	//
	//Fees incoming is the amount of fees in millisatoshis that we
	//attribute to the channel for its role as the incoming channel in
	//forwards.
	FeesIncomingMsat     int64    `protobuf:"varint,4,opt,name=fees_incoming_msat,json=feesIncomingMsat,proto3" json:"fees_incoming_msat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairReport) Reset()         { *m = PairReport{} }
func (m *PairReport) String() string { return proto.CompactTextString(m) }
func (*PairReport) ProtoMessage()    {}
func (*PairReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *PairReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairReport.Unmarshal(m, b)
}
func (m *PairReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairReport.Marshal(b, m, deterministic)
}
func (m *PairReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairReport.Merge(m, src)
}
func (m *PairReport) XXX_Size() int {
	return xxx_messageInfo_PairReport.Size(m)
}
func (m *PairReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PairReport.DiscardUnknown(m)
}

var xxx_messageInfo_PairReport proto.InternalMessageInfo

func (m *PairReport) GetAmountOutgoingMsat() int64 {
	if m != nil {
		return m.AmountOutgoingMsat
	}
	return 0
}

func (m *PairReport) GetFeesOutgoingMsat() int64 {
	if m != nil {
		return m.FeesOutgoingMsat
	}
	return 0
}

func (m *PairReport) GetAmountIncomingMsat() int64 {
	if m != nil {
		return m.AmountIncomingMsat
	}
	return 0
}

func (m *PairReport) GetFeesIncomingMsat() int64 {
	if m != nil {
		return m.FeesIncomingMsat
	}
	return 0
}

type ChannelInsightsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInsightsRequest) Reset()         { *m = ChannelInsightsRequest{} }
func (m *ChannelInsightsRequest) String() string { return proto.CompactTextString(m) }
func (*ChannelInsightsRequest) ProtoMessage()    {}
func (*ChannelInsightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *ChannelInsightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsightsRequest.Unmarshal(m, b)
}
func (m *ChannelInsightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsightsRequest.Marshal(b, m, deterministic)
}
func (m *ChannelInsightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsightsRequest.Merge(m, src)
}
func (m *ChannelInsightsRequest) XXX_Size() int {
	return xxx_messageInfo_ChannelInsightsRequest.Size(m)
}
func (m *ChannelInsightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsightsRequest proto.InternalMessageInfo

type ChannelInsightsResponse struct {
	// Insights for the set of currently open channels.
	ChannelInsights      []*ChannelInsight `protobuf:"bytes,1,rep,name=channel_insights,json=channelInsights,proto3" json:"channel_insights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelInsightsResponse) Reset()         { *m = ChannelInsightsResponse{} }
func (m *ChannelInsightsResponse) String() string { return proto.CompactTextString(m) }
func (*ChannelInsightsResponse) ProtoMessage()    {}
func (*ChannelInsightsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *ChannelInsightsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsightsResponse.Unmarshal(m, b)
}
func (m *ChannelInsightsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsightsResponse.Marshal(b, m, deterministic)
}
func (m *ChannelInsightsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsightsResponse.Merge(m, src)
}
func (m *ChannelInsightsResponse) XXX_Size() int {
	return xxx_messageInfo_ChannelInsightsResponse.Size(m)
}
func (m *ChannelInsightsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsightsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsightsResponse proto.InternalMessageInfo

func (m *ChannelInsightsResponse) GetChannelInsights() []*ChannelInsight {
	if m != nil {
		return m.ChannelInsights
	}
	return nil
}

type ChannelInsight struct {
	// The outpoint of the channel's funding transaction.
	ChanPoint string `protobuf:"bytes,1,opt,name=chan_point,json=chanPoint,proto3" json:"chan_point,omitempty"`
	//
	//The amount of time in seconds that we have monitored the channel peer's
	//uptime for.
	MonitoredSeconds uint64 `protobuf:"varint,2,opt,name=monitored_seconds,json=monitoredSeconds,proto3" json:"monitored_seconds,omitempty"`
	//
	//The amount of time in seconds that the channel peer has been online over
	//the period it has been monitored for.
	UptimeSeconds uint64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	//
	//The volume, in millisatoshis, that has been forwarded with this channel as
	//the incoming channel.
	VolumeIncomingMsat int64 `protobuf:"varint,4,opt,name=volume_incoming_msat,json=volumeIncomingMsat,proto3" json:"volume_incoming_msat,omitempty"`
	//
	//The volume, in millisatoshis, that has been forwarded with this channel as
	//the outgoing channel.
	VolumeOutgoingMsat int64 `protobuf:"varint,5,opt,name=volume_outgoing_msat,json=volumeOutgoingMsat,proto3" json:"volume_outgoing_msat,omitempty"`
	//
	//The total fees earned by this channel for its participation in forwards,
	//expressed in millisatoshis. Note that we attribute fees evenly across
	//incoming and outgoing channels.
	FeesEarnedMsat int64 `protobuf:"varint,6,opt,name=fees_earned_msat,json=feesEarnedMsat,proto3" json:"fees_earned_msat,omitempty"`
	// The number of confirmations the funding transaction has.
	Confirmations uint32 `protobuf:"varint,7,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	// True if the channel is private.
	Private              bool     `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInsight) Reset()         { *m = ChannelInsight{} }
func (m *ChannelInsight) String() string { return proto.CompactTextString(m) }
func (*ChannelInsight) ProtoMessage()    {}
func (*ChannelInsight) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *ChannelInsight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsight.Unmarshal(m, b)
}
func (m *ChannelInsight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsight.Marshal(b, m, deterministic)
}
func (m *ChannelInsight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsight.Merge(m, src)
}
func (m *ChannelInsight) XXX_Size() int {
	return xxx_messageInfo_ChannelInsight.Size(m)
}
func (m *ChannelInsight) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsight.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsight proto.InternalMessageInfo

func (m *ChannelInsight) GetChanPoint() string {
	if m != nil {
		return m.ChanPoint
	}
	return ""
}

func (m *ChannelInsight) GetMonitoredSeconds() uint64 {
	if m != nil {
		return m.MonitoredSeconds
	}
	return 0
}

func (m *ChannelInsight) GetUptimeSeconds() uint64 {
	if m != nil {
		return m.UptimeSeconds
	}
	return 0
}

func (m *ChannelInsight) GetVolumeIncomingMsat() int64 {
	if m != nil {
		return m.VolumeIncomingMsat
	}
	return 0
}

func (m *ChannelInsight) GetVolumeOutgoingMsat() int64 {
	if m != nil {
		return m.VolumeOutgoingMsat
	}
	return 0
}

func (m *ChannelInsight) GetFeesEarnedMsat() int64 {
	if m != nil {
		return m.FeesEarnedMsat
	}
	return 0
}

func (m *ChannelInsight) GetConfirmations() uint32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *ChannelInsight) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type FiatEstimateRequest struct {
	Requests             []*FiatEstimateRequest_PriceRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Granularity          FiatEstimateRequest_Granularity     `protobuf:"varint,2,opt,name=granularity,proto3,enum=frdrpc.FiatEstimateRequest_Granularity" json:"granularity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *FiatEstimateRequest) Reset()         { *m = FiatEstimateRequest{} }
func (m *FiatEstimateRequest) String() string { return proto.CompactTextString(m) }
func (*FiatEstimateRequest) ProtoMessage()    {}
func (*FiatEstimateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *FiatEstimateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FiatEstimateRequest.Unmarshal(m, b)
}
func (m *FiatEstimateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FiatEstimateRequest.Marshal(b, m, deterministic)
}
func (m *FiatEstimateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FiatEstimateRequest.Merge(m, src)
}
func (m *FiatEstimateRequest) XXX_Size() int {
	return xxx_messageInfo_FiatEstimateRequest.Size(m)
}
func (m *FiatEstimateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FiatEstimateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FiatEstimateRequest proto.InternalMessageInfo

func (m *FiatEstimateRequest) GetRequests() []*FiatEstimateRequest_PriceRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *FiatEstimateRequest) GetGranularity() FiatEstimateRequest_Granularity {
	if m != nil {
		return m.Granularity
	}
	return FiatEstimateRequest_UNKNOWN
}

type FiatEstimateRequest_PriceRequest struct {
	// id is a unique identifier for the request.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The amount to be converted to fiat in millisatoshis.
	AmountMsat uint64 `protobuf:"varint,2,opt,name=amount_msat,json=amountMsat,proto3" json:"amount_msat,omitempty"`
	// The unix timestamp at which the price should be quoted.
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FiatEstimateRequest_PriceRequest) Reset()         { *m = FiatEstimateRequest_PriceRequest{} }
func (m *FiatEstimateRequest_PriceRequest) String() string { return proto.CompactTextString(m) }
func (*FiatEstimateRequest_PriceRequest) ProtoMessage()    {}
func (*FiatEstimateRequest_PriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12, 0}
}

func (m *FiatEstimateRequest_PriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FiatEstimateRequest_PriceRequest.Unmarshal(m, b)
}
func (m *FiatEstimateRequest_PriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FiatEstimateRequest_PriceRequest.Marshal(b, m, deterministic)
}
func (m *FiatEstimateRequest_PriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FiatEstimateRequest_PriceRequest.Merge(m, src)
}
func (m *FiatEstimateRequest_PriceRequest) XXX_Size() int {
	return xxx_messageInfo_FiatEstimateRequest_PriceRequest.Size(m)
}
func (m *FiatEstimateRequest_PriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FiatEstimateRequest_PriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FiatEstimateRequest_PriceRequest proto.InternalMessageInfo

func (m *FiatEstimateRequest_PriceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FiatEstimateRequest_PriceRequest) GetAmountMsat() uint64 {
	if m != nil {
		return m.AmountMsat
	}
	return 0
}

func (m *FiatEstimateRequest_PriceRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type FiatEstimateResponse struct {
	FiatValues           map[string]string `protobuf:"bytes,1,rep,name=fiat_values,json=fiatValues,proto3" json:"fiat_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FiatEstimateResponse) Reset()         { *m = FiatEstimateResponse{} }
func (m *FiatEstimateResponse) String() string { return proto.CompactTextString(m) }
func (*FiatEstimateResponse) ProtoMessage()    {}
func (*FiatEstimateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *FiatEstimateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FiatEstimateResponse.Unmarshal(m, b)
}
func (m *FiatEstimateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FiatEstimateResponse.Marshal(b, m, deterministic)
}
func (m *FiatEstimateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FiatEstimateResponse.Merge(m, src)
}
func (m *FiatEstimateResponse) XXX_Size() int {
	return xxx_messageInfo_FiatEstimateResponse.Size(m)
}
func (m *FiatEstimateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FiatEstimateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FiatEstimateResponse proto.InternalMessageInfo

func (m *FiatEstimateResponse) GetFiatValues() map[string]string {
	if m != nil {
		return m.FiatValues
	}
	return nil
}

func init() {
	proto.RegisterEnum("frdrpc.CloseRecommendationRequest_Metric", CloseRecommendationRequest_Metric_name, CloseRecommendationRequest_Metric_value)
	proto.RegisterEnum("frdrpc.FiatEstimateRequest_Granularity", FiatEstimateRequest_Granularity_name, FiatEstimateRequest_Granularity_value)
	proto.RegisterType((*CloseRecommendationRequest)(nil), "frdrpc.CloseRecommendationRequest")
	proto.RegisterType((*OutlierRecommendationsRequest)(nil), "frdrpc.OutlierRecommendationsRequest")
	proto.RegisterType((*ThresholdRecommendationsRequest)(nil), "frdrpc.ThresholdRecommendationsRequest")
	proto.RegisterType((*CloseRecommendationsResponse)(nil), "frdrpc.CloseRecommendationsResponse")
	proto.RegisterType((*Recommendation)(nil), "frdrpc.Recommendation")
	proto.RegisterType((*RevenueReportRequest)(nil), "frdrpc.RevenueReportRequest")
	proto.RegisterType((*RevenueReportResponse)(nil), "frdrpc.RevenueReportResponse")
	proto.RegisterType((*RevenueReport)(nil), "frdrpc.RevenueReport")
	proto.RegisterMapType((map[string]*PairReport)(nil), "frdrpc.RevenueReport.PairReportsEntry")
	proto.RegisterType((*PairReport)(nil), "frdrpc.PairReport")
	proto.RegisterType((*ChannelInsightsRequest)(nil), "frdrpc.ChannelInsightsRequest")
	proto.RegisterType((*ChannelInsightsResponse)(nil), "frdrpc.ChannelInsightsResponse")
	proto.RegisterType((*ChannelInsight)(nil), "frdrpc.ChannelInsight")
	proto.RegisterType((*FiatEstimateRequest)(nil), "frdrpc.FiatEstimateRequest")
	proto.RegisterType((*FiatEstimateRequest_PriceRequest)(nil), "frdrpc.FiatEstimateRequest.PriceRequest")
	proto.RegisterType((*FiatEstimateResponse)(nil), "frdrpc.FiatEstimateResponse")
	proto.RegisterMapType((map[string]string)(nil), "frdrpc.FiatEstimateResponse.FiatValuesEntry")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 1280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4d, 0x6f, 0x1b, 0x55,
	0x17, 0x7e, 0xc7, 0x4e, 0xec, 0xf8, 0x38, 0x76, 0xa6, 0x37, 0x69, 0x5e, 0xe3, 0xa6, 0x34, 0x1a,
	0xb5, 0xd4, 0xa5, 0xc5, 0x6e, 0xcd, 0x06, 0x21, 0x21, 0x11, 0xa5, 0x93, 0xd6, 0xa2, 0xb6, 0xa3,
	0x89, 0x9d, 0x52, 0x09, 0x34, 0x1a, 0xc6, 0x37, 0xce, 0x05, 0xcf, 0x47, 0xef, 0x5c, 0x5b, 0x8a,
	0x10, 0x1b, 0xd6, 0x48, 0x2c, 0x2a, 0x24, 0x36, 0xdd, 0xf1, 0x23, 0xf8, 0x11, 0x6c, 0x10, 0xe2,
	0x1f, 0xf0, 0x23, 0x58, 0xa2, 0xfb, 0x31, 0x5f, 0xae, 0x93, 0xb2, 0x61, 0xe7, 0x79, 0x9e, 0xe7,
	0xde, 0xe7, 0xcc, 0x39, 0x77, 0xce, 0x3d, 0x86, 0x0a, 0x0d, 0xdd, 0x76, 0x48, 0x03, 0x16, 0xa0,
	0xd2, 0x19, 0x9d, 0xd0, 0xd0, 0x6d, 0xee, 0x4d, 0x83, 0x60, 0x3a, 0xc3, 0x1d, 0x27, 0x24, 0x1d,
	0xc7, 0xf7, 0x03, 0xe6, 0x30, 0x12, 0xf8, 0x91, 0x54, 0x19, 0x7f, 0x6b, 0xd0, 0x3c, 0x9c, 0x05,
	0x11, 0xb6, 0xb0, 0x1b, 0x78, 0x1e, 0xf6, 0x27, 0x82, 0xb6, 0xf0, 0xcb, 0x39, 0x8e, 0x18, 0xba,
	0x0f, 0xd7, 0x3c, 0xe2, 0x13, 0x6f, 0xee, 0xd9, 0x5e, 0xe0, 0x13, 0x16, 0x50, 0x3c, 0x69, 0x68,
	0xfb, 0x5a, 0xab, 0x68, 0xe9, 0x8a, 0xe8, 0xc7, 0x38, 0x3a, 0x80, 0x92, 0x87, 0x19, 0x25, 0x6e,
	0xa3, 0xb0, 0xaf, 0xb5, 0xea, 0xdd, 0x7b, 0x6d, 0x19, 0x42, 0xfb, 0x72, 0x83, 0x76, 0x5f, 0x2c,
	0xb0, 0xd4, 0x42, 0xe3, 0x6b, 0x28, 0x49, 0x04, 0x55, 0xa1, 0x3c, 0x1e, 0x7c, 0x36, 0x18, 0x3e,
	0x1f, 0xe8, 0xff, 0x43, 0x00, 0xa5, 0xf1, 0xf1, 0xa8, 0xd7, 0x37, 0x75, 0x8d, 0x13, 0x96, 0x79,
	0x6a, 0x0e, 0xc6, 0xa6, 0x5e, 0x40, 0xdb, 0xb0, 0xd5, 0x1b, 0x1c, 0x0e, 0xfb, 0xbd, 0xc1, 0x13,
	0xfb, 0x74, 0xf8, 0x6c, 0xdc, 0x37, 0xf5, 0x22, 0x07, 0x87, 0xe3, 0xd1, 0x93, 0x61, 0x06, 0x5c,
	0x43, 0x3a, 0x6c, 0x8e, 0x86, 0xa3, 0x83, 0x67, 0x31, 0xb2, 0x6e, 0xbc, 0xd2, 0xe0, 0xe6, 0x70,
	0xce, 0x66, 0x04, 0xd3, 0x7c, 0x6c, 0x51, 0xfc, 0xf6, 0x87, 0x50, 0xa5, 0xd8, 0xb5, 0xa9, 0x7c,
	0x14, 0xef, 0x5d, 0xed, 0x1a, 0x6f, 0x7f, 0x2b, 0x0b, 0x28, 0x76, 0xe3, 0x4d, 0x3e, 0x00, 0x14,
	0x48, 0x17, 0xdb, 0x9b, 0xcf, 0x18, 0x09, 0xf9, 0x4f, 0x91, 0xa1, 0x82, 0x75, 0x4d, 0x31, 0xfd,
	0x84, 0x30, 0x7e, 0xd4, 0xe0, 0xd6, 0xe8, 0x9c, 0xe2, 0xe8, 0x3c, 0x98, 0x4d, 0xfe, 0xcb, 0xb8,
	0xee, 0xc2, 0x16, 0x8b, 0x7d, 0xec, 0x85, 0x33, 0x9b, 0x63, 0x15, 0x54, 0x3d, 0x81, 0x4f, 0x39,
	0x6a, 0xfc, 0xaa, 0xc1, 0xde, 0x8a, 0x3d, 0x23, 0x0b, 0x47, 0x61, 0xe0, 0x47, 0x18, 0xdd, 0x81,
	0x3a, 0x0b, 0x98, 0x33, 0xb3, 0xdd, 0x73, 0xc7, 0xf7, 0xf1, 0x2c, 0x12, 0x11, 0xad, 0x5b, 0x35,
	0x81, 0x1e, 0x2a, 0x10, 0x75, 0x60, 0xdb, 0x0d, 0xfc, 0x88, 0x4c, 0x30, 0xc5, 0x93, 0x54, 0x5b,
	0x10, 0x5a, 0x94, 0x52, 0xc9, 0x82, 0x4f, 0x61, 0x8b, 0xe6, 0x2d, 0x1b, 0xc5, 0xfd, 0x62, 0xab,
	0xda, 0xdd, 0x8d, 0x5f, 0x75, 0xe9, 0x2d, 0x97, 0xe5, 0x86, 0x0f, 0xf5, 0xbc, 0x04, 0xdd, 0x04,
	0xe0, 0xce, 0x76, 0x18, 0x10, 0x5f, 0x66, 0xae, 0x62, 0x55, 0x38, 0x72, 0xcc, 0x01, 0xb4, 0x03,
	0xeb, 0xd9, 0x54, 0xc8, 0x07, 0x9e, 0xaa, 0x64, 0x67, 0xdb, 0xe5, 0xa9, 0x68, 0x14, 0xf7, 0xb5,
	0xd6, 0x86, 0x55, 0x4f, 0x60, 0x91, 0x20, 0xe3, 0x25, 0xec, 0x58, 0x78, 0x81, 0xfd, 0x39, 0xb6,
	0x70, 0x18, 0x50, 0x16, 0xe7, 0xfa, 0x16, 0x54, 0x53, 0x57, 0x9e, 0x9e, 0x62, 0xab, 0x62, 0x41,
	0x62, 0x1b, 0xf1, 0xb0, 0x22, 0xe6, 0x50, 0x66, 0x33, 0xe2, 0x49, 0xf3, 0x35, 0xab, 0x22, 0x90,
	0x11, 0xf1, 0x30, 0x7a, 0x07, 0x36, 0xb8, 0xb5, 0x20, 0x8b, 0x82, 0x2c, 0x63, 0x7f, 0xc2, 0x29,
	0xe3, 0x29, 0x5c, 0x5f, 0xb2, 0x54, 0x55, 0xe9, 0x40, 0x99, 0x0a, 0x44, 0xfa, 0x55, 0xbb, 0xd7,
	0xd3, 0xac, 0x65, 0xf5, 0xb1, 0xca, 0xf8, 0x53, 0x83, 0x5a, 0x8e, 0x12, 0x85, 0x75, 0xe8, 0x14,
	0xb3, 0xb8, 0x5a, 0x2a, 0x61, 0x35, 0x89, 0xaa, 0x42, 0xa1, 0x1e, 0x6c, 0x86, 0x0e, 0xa1, 0x76,
	0x6c, 0x57, 0x10, 0x76, 0xef, 0xad, 0xb4, 0x6b, 0x1f, 0x3b, 0x84, 0xca, 0x9f, 0x91, 0xe9, 0x33,
	0x7a, 0x61, 0x55, 0xc3, 0x14, 0x69, 0x5a, 0xa0, 0x2f, 0x0b, 0x90, 0x0e, 0xc5, 0x6f, 0xf0, 0x85,
	0xb2, 0xe6, 0x3f, 0x51, 0x2b, 0x5b, 0xa5, 0x6a, 0x17, 0xc5, 0x4e, 0xe9, 0x52, 0x55, 0xb9, 0x8f,
	0x0b, 0x1f, 0x69, 0xc6, 0x6f, 0x1a, 0x40, 0xca, 0xa0, 0x87, 0xb0, 0xe3, 0x78, 0xc1, 0xdc, 0x67,
	0x76, 0x30, 0x67, 0xd3, 0x80, 0xf8, 0x53, 0xdb, 0x8b, 0x1c, 0xa6, 0xba, 0x1a, 0x92, 0xdc, 0x50,
	0x51, 0xfd, 0xc8, 0x61, 0xe8, 0x01, 0xa0, 0x33, 0x8c, 0xa3, 0x25, 0x7d, 0x41, 0x76, 0x41, 0xce,
	0xe4, 0xd4, 0xe9, 0xfe, 0xc4, 0x77, 0x03, 0x2f, 0xd1, 0x17, 0xb3, 0xfb, 0xf7, 0x14, 0x95, 0xdb,
	0x3f, 0xaf, 0x5f, 0x4b, 0xf7, 0xcf, 0xaa, 0x8d, 0x06, 0xec, 0xaa, 0xc4, 0xf7, 0xfc, 0x88, 0x4c,
	0xcf, 0x59, 0xdc, 0x16, 0x8c, 0x2f, 0xe0, 0xff, 0x6f, 0x30, 0xea, 0x30, 0x1c, 0x80, 0xae, 0x4a,
	0x68, 0x13, 0xc5, 0xa9, 0x53, 0x91, 0x7c, 0x4b, 0xf9, 0xa5, 0xd6, 0x96, 0x9b, 0xdf, 0xca, 0xf8,
	0xbd, 0x00, 0xf5, 0xbc, 0xe6, 0x6d, 0x1f, 0x13, 0xbf, 0x3c, 0xe2, 0xcb, 0xc1, 0x8e, 0xb0, 0x1b,
	0xf8, 0x93, 0x48, 0x9d, 0x6d, 0x3d, 0x21, 0x4e, 0x24, 0xce, 0xcf, 0xda, 0x3c, 0xe4, 0x07, 0x3c,
	0x51, 0xca, 0x83, 0x5e, 0x93, 0x68, 0x2c, 0x7b, 0x08, 0x3b, 0x8b, 0x60, 0x36, 0xf7, 0xf0, 0xca,
	0x6c, 0x21, 0xc9, 0xe5, 0xb2, 0x9b, 0xae, 0xc8, 0xd7, 0x6f, 0x3d, 0xbb, 0x22, 0x57, 0xc1, 0x16,
	0x88, 0xac, 0xdb, 0xd8, 0xa1, 0x3e, 0x9e, 0x48, 0x75, 0x49, 0xa8, 0xeb, 0x1c, 0x37, 0x05, 0x2c,
	0x94, 0xb7, 0xa1, 0xe6, 0x06, 0xfe, 0x19, 0xa1, 0x9e, 0xea, 0x4f, 0xe5, 0x7d, 0xad, 0x55, 0xb3,
	0xf2, 0x20, 0x6a, 0x40, 0x39, 0xa4, 0x64, 0xe1, 0x30, 0xdc, 0xd8, 0x10, 0x6d, 0x23, 0x7e, 0x34,
	0x5e, 0x17, 0x61, 0xfb, 0x88, 0x38, 0xcc, 0x8c, 0x18, 0xf1, 0x1c, 0x86, 0xe3, 0x7e, 0xf1, 0x18,
	0x36, 0x54, 0x73, 0x8f, 0xcb, 0xd4, 0x8a, 0xcb, 0xb4, 0x42, 0xde, 0x3e, 0xa6, 0xc4, 0x8d, 0x1f,
	0xac, 0x64, 0x25, 0xea, 0x41, 0x75, 0x4a, 0x1d, 0x7f, 0x3e, 0x73, 0x28, 0x61, 0x17, 0xea, 0x52,
	0xbe, 0x7b, 0xd5, 0x46, 0x4f, 0x52, 0xb9, 0x95, 0x5d, 0xdb, 0xfc, 0x12, 0x36, 0xb3, 0x26, 0xa8,
	0x0e, 0x05, 0x32, 0x51, 0x15, 0x2f, 0x90, 0x09, 0x6f, 0x70, 0xea, 0xd0, 0x27, 0xdf, 0xc6, 0x9a,
	0x05, 0x12, 0x12, 0x99, 0xda, 0x83, 0x0a, 0x2f, 0x63, 0xc4, 0x1c, 0x2f, 0x54, 0x9f, 0x42, 0x0a,
	0x18, 0x3f, 0x69, 0x50, 0xcd, 0x78, 0xbf, 0x71, 0xf9, 0xf7, 0x7b, 0x83, 0xf1, 0x88, 0x5f, 0xfe,
	0x3a, 0x6c, 0x1e, 0xf5, 0x4e, 0x4d, 0x5b, 0x02, 0x27, 0x72, 0x02, 0x38, 0xea, 0x1d, 0x8d, 0x4c,
	0x73, 0x90, 0x80, 0x45, 0x84, 0xa0, 0x3e, 0x7a, 0xda, 0xb3, 0x46, 0x2f, 0x12, 0x6c, 0x0d, 0x6d,
	0xc0, 0xda, 0xd3, 0xe1, 0xd8, 0xd2, 0xd7, 0x51, 0x0d, 0x2a, 0x27, 0xbd, 0xcf, 0x6d, 0xfe, 0x74,
	0xa2, 0x97, 0xc4, 0x64, 0xf0, 0xdc, 0x7c, 0x76, 0x6a, 0x2a, 0xa4, 0x8c, 0xca, 0x50, 0x7c, 0x7c,
	0xf0, 0x42, 0xdf, 0x30, 0x7e, 0xd1, 0x60, 0x27, 0x9f, 0x27, 0xf5, 0x3d, 0xf5, 0xa1, 0x7a, 0x46,
	0x1c, 0x26, 0xef, 0xcd, 0xb8, 0x46, 0x0f, 0x56, 0xa7, 0x56, 0x2e, 0x11, 0xa0, 0xb8, 0x50, 0x55,
	0xdf, 0x83, 0xb3, 0x04, 0x68, 0x7e, 0x02, 0x5b, 0x4b, 0xf4, 0x8a, 0xae, 0x97, 0xbb, 0x9b, 0x2a,
	0x99, 0x0e, 0xd7, 0xfd, 0x61, 0x1d, 0x6a, 0x47, 0x0e, 0x75, 0x26, 0xce, 0xc5, 0x09, 0xa6, 0x0b,
	0x4c, 0xd1, 0xcf, 0x1a, 0xec, 0xae, 0x9e, 0x6d, 0xd0, 0x9d, 0x38, 0xca, 0x2b, 0x67, 0x9f, 0xe6,
	0xed, 0x2b, 0xc6, 0x89, 0xa4, 0xaf, 0x18, 0x8f, 0xbe, 0xff, 0xe3, 0xaf, 0x57, 0x85, 0xfb, 0xe8,
	0x5e, 0x67, 0xf1, 0xa8, 0x73, 0x26, 0x43, 0xe8, 0xa8, 0xa1, 0x26, 0xea, 0x7c, 0x9b, 0x99, 0x52,
	0xda, 0x72, 0xc2, 0xfb, 0x0e, 0xbd, 0xd6, 0xa0, 0x71, 0xd9, 0x80, 0x83, 0x92, 0xd3, 0xf9, 0x96,
	0x11, 0xe8, 0x5f, 0x86, 0xd7, 0x15, 0xe1, 0x3d, 0x40, 0xef, 0x67, 0xc3, 0x4b, 0xc6, 0x9b, 0xd5,
	0xf1, 0x91, 0xe5, 0x5b, 0x70, 0x6f, 0xf5, 0xbd, 0xa9, 0x02, 0xb9, 0x79, 0x09, 0xab, 0x22, 0xb8,
	0x21, 0x22, 0xb8, 0x8e, 0xb6, 0xb3, 0x11, 0x50, 0x29, 0x45, 0x21, 0x6c, 0x2d, 0x35, 0x6c, 0xf4,
	0xee, 0xea, 0x76, 0x9c, 0xbc, 0xf7, 0xad, 0x4b, 0x79, 0x65, 0xb8, 0x27, 0x0c, 0x77, 0xd1, 0x4e,
	0xd6, 0x30, 0xee, 0xf9, 0xc8, 0x85, 0xcd, 0xec, 0xe1, 0x44, 0x37, 0xae, 0xe8, 0x06, 0xcd, 0xbd,
	0xab, 0xce, 0xb3, 0xd1, 0x10, 0x46, 0x08, 0xe9, 0x59, 0x23, 0x7e, 0xa6, 0xbf, 0x2a, 0x89, 0xbf,
	0x16, 0x1f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x93, 0x3d, 0x7d, 0xb6, 0x8d, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaradayServerClient is the client API for FaradayServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaradayServerClient interface {
	//* frcli: `outliers`
	//Get close recommendations for currently open channels based on whether it is
	//an outlier.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/outliers/REVENUE?rec_request.minimum_monitored=123
	OutlierRecommendations(ctx context.Context, in *OutlierRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error)
	//* frcli: `threshold`
	//Get close recommendations for currently open channels based whether they are
	//below a set threshold.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/threshold/UPTIME?rec_request.minimum_monitored=123
	ThresholdRecommendations(ctx context.Context, in *ThresholdRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error)
	//* frcli: `revenue`
	//Get a pairwise revenue report for a channel.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/revenue
	RevenueReport(ctx context.Context, in *RevenueReportRequest, opts ...grpc.CallOption) (*RevenueReportResponse, error)
	//* frcli: `insights`
	//List currently open channel with routing and uptime information.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/insights
	ChannelInsights(ctx context.Context, in *ChannelInsightsRequest, opts ...grpc.CallOption) (*ChannelInsightsResponse, error)
	//* frcli:
	//Get fiat prices for btc.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/fiat
	FiatEstimate(ctx context.Context, in *FiatEstimateRequest, opts ...grpc.CallOption) (*FiatEstimateResponse, error)
}

type faradayServerClient struct {
	cc *grpc.ClientConn
}

func NewFaradayServerClient(cc *grpc.ClientConn) FaradayServerClient {
	return &faradayServerClient{cc}
}

func (c *faradayServerClient) OutlierRecommendations(ctx context.Context, in *OutlierRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error) {
	out := new(CloseRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/OutlierRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) ThresholdRecommendations(ctx context.Context, in *ThresholdRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error) {
	out := new(CloseRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/ThresholdRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) RevenueReport(ctx context.Context, in *RevenueReportRequest, opts ...grpc.CallOption) (*RevenueReportResponse, error) {
	out := new(RevenueReportResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/RevenueReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) ChannelInsights(ctx context.Context, in *ChannelInsightsRequest, opts ...grpc.CallOption) (*ChannelInsightsResponse, error) {
	out := new(ChannelInsightsResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/ChannelInsights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faradayServerClient) FiatEstimate(ctx context.Context, in *FiatEstimateRequest, opts ...grpc.CallOption) (*FiatEstimateResponse, error) {
	out := new(FiatEstimateResponse)
	err := c.cc.Invoke(ctx, "/frdrpc.FaradayServer/FiatEstimate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaradayServerServer is the server API for FaradayServer service.
type FaradayServerServer interface {
	//* frcli: `outliers`
	//Get close recommendations for currently open channels based on whether it is
	//an outlier.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/outliers/REVENUE?rec_request.minimum_monitored=123
	OutlierRecommendations(context.Context, *OutlierRecommendationsRequest) (*CloseRecommendationsResponse, error)
	//* frcli: `threshold`
	//Get close recommendations for currently open channels based whether they are
	//below a set threshold.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/threshold/UPTIME?rec_request.minimum_monitored=123
	ThresholdRecommendations(context.Context, *ThresholdRecommendationsRequest) (*CloseRecommendationsResponse, error)
	//* frcli: `revenue`
	//Get a pairwise revenue report for a channel.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/revenue
	RevenueReport(context.Context, *RevenueReportRequest) (*RevenueReportResponse, error)
	//* frcli: `insights`
	//List currently open channel with routing and uptime information.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/insights
	ChannelInsights(context.Context, *ChannelInsightsRequest) (*ChannelInsightsResponse, error)
	//* frcli:
	//Get fiat prices for btc.
	//
	//Example request:
	//http://localhost:8466/v1/faraday/fiat
	FiatEstimate(context.Context, *FiatEstimateRequest) (*FiatEstimateResponse, error)
}

func RegisterFaradayServerServer(s *grpc.Server, srv FaradayServerServer) {
	s.RegisterService(&_FaradayServer_serviceDesc, srv)
}

func _FaradayServer_OutlierRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutlierRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).OutlierRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/OutlierRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).OutlierRecommendations(ctx, req.(*OutlierRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_ThresholdRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThresholdRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).ThresholdRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/ThresholdRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).ThresholdRecommendations(ctx, req.(*ThresholdRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_RevenueReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevenueReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).RevenueReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/RevenueReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).RevenueReport(ctx, req.(*RevenueReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_ChannelInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).ChannelInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/ChannelInsights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).ChannelInsights(ctx, req.(*ChannelInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaradayServer_FiatEstimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FiatEstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaradayServerServer).FiatEstimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frdrpc.FaradayServer/FiatEstimate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaradayServerServer).FiatEstimate(ctx, req.(*FiatEstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FaradayServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frdrpc.FaradayServer",
	HandlerType: (*FaradayServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OutlierRecommendations",
			Handler:    _FaradayServer_OutlierRecommendations_Handler,
		},
		{
			MethodName: "ThresholdRecommendations",
			Handler:    _FaradayServer_ThresholdRecommendations_Handler,
		},
		{
			MethodName: "RevenueReport",
			Handler:    _FaradayServer_RevenueReport_Handler,
		},
		{
			MethodName: "ChannelInsights",
			Handler:    _FaradayServer_ChannelInsights_Handler,
		},
		{
			MethodName: "FiatEstimate",
			Handler:    _FaradayServer_FiatEstimate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
