// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package trmrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CloseRecommendationRequest_Metric int32

const (
	CloseRecommendationRequest_UNKNOWN         CloseRecommendationRequest_Metric = 0
	CloseRecommendationRequest_UPTIME          CloseRecommendationRequest_Metric = 1
	CloseRecommendationRequest_REVENUE         CloseRecommendationRequest_Metric = 2
	CloseRecommendationRequest_INCOMING_VOLUME CloseRecommendationRequest_Metric = 3
	CloseRecommendationRequest_OUTGOING_VOLUME CloseRecommendationRequest_Metric = 4
	CloseRecommendationRequest_TOTAL_VOLUME    CloseRecommendationRequest_Metric = 5
)

var CloseRecommendationRequest_Metric_name = map[int32]string{
	0: "UNKNOWN",
	1: "UPTIME",
	2: "REVENUE",
	3: "INCOMING_VOLUME",
	4: "OUTGOING_VOLUME",
	5: "TOTAL_VOLUME",
}

var CloseRecommendationRequest_Metric_value = map[string]int32{
	"UNKNOWN":         0,
	"UPTIME":          1,
	"REVENUE":         2,
	"INCOMING_VOLUME": 3,
	"OUTGOING_VOLUME": 4,
	"TOTAL_VOLUME":    5,
}

func (x CloseRecommendationRequest_Metric) String() string {
	return proto.EnumName(CloseRecommendationRequest_Metric_name, int32(x))
}

func (CloseRecommendationRequest_Metric) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0, 0}
}

type CloseRecommendationRequest struct {
	//
	//The minimum amount of time in seconds that a channel should have been
	//monitored by lnd to be eligible for close. This value is in place to
	//protect against closing of newer channels.
	MinimumMonitored int64 `protobuf:"varint,1,opt,name=minimum_monitored,json=minimumMonitored,proto3" json:"minimum_monitored,omitempty"`
	//
	//The data point base close recommendations on. Available options are:
	//Uptime: ratio of channel peer's uptime to the period they have been
	//monitored to.
	//Revenue: the revenue that the channel has produced per block that its
	//funding transaction has been confirmed for.
	Metric               CloseRecommendationRequest_Metric `protobuf:"varint,2,opt,name=metric,proto3,enum=trmrpc.CloseRecommendationRequest_Metric" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CloseRecommendationRequest) Reset()         { *m = CloseRecommendationRequest{} }
func (m *CloseRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRecommendationRequest) ProtoMessage()    {}
func (*CloseRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *CloseRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRecommendationRequest.Unmarshal(m, b)
}
func (m *CloseRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *CloseRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRecommendationRequest.Merge(m, src)
}
func (m *CloseRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRecommendationRequest.Size(m)
}
func (m *CloseRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRecommendationRequest proto.InternalMessageInfo

func (m *CloseRecommendationRequest) GetMinimumMonitored() int64 {
	if m != nil {
		return m.MinimumMonitored
	}
	return 0
}

func (m *CloseRecommendationRequest) GetMetric() CloseRecommendationRequest_Metric {
	if m != nil {
		return m.Metric
	}
	return CloseRecommendationRequest_UNKNOWN
}

type OutlierRecommendationsRequest struct {
	//
	//The parameters that are common to all close recommendations.
	RecRequest *CloseRecommendationRequest `protobuf:"bytes,1,opt,name=rec_request,json=recRequest,proto3" json:"rec_request,omitempty"`
	//
	//The number of inter-quartile ranges a value needs to be beneath the lower
	//quartile/ above the upper quartile to be considered a lower/upper outlier.
	//Lower values will be more aggressive in recommending channel closes, and
	//upper values will be more conservative. Recommended values are 1.5 for
	//aggressive recommendations and 3 for conservative recommendations.
	OutlierMultiplier    float32  `protobuf:"fixed32,2,opt,name=outlier_multiplier,json=outlierMultiplier,proto3" json:"outlier_multiplier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutlierRecommendationsRequest) Reset()         { *m = OutlierRecommendationsRequest{} }
func (m *OutlierRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*OutlierRecommendationsRequest) ProtoMessage()    {}
func (*OutlierRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *OutlierRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutlierRecommendationsRequest.Unmarshal(m, b)
}
func (m *OutlierRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutlierRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *OutlierRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutlierRecommendationsRequest.Merge(m, src)
}
func (m *OutlierRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_OutlierRecommendationsRequest.Size(m)
}
func (m *OutlierRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutlierRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutlierRecommendationsRequest proto.InternalMessageInfo

func (m *OutlierRecommendationsRequest) GetRecRequest() *CloseRecommendationRequest {
	if m != nil {
		return m.RecRequest
	}
	return nil
}

func (m *OutlierRecommendationsRequest) GetOutlierMultiplier() float32 {
	if m != nil {
		return m.OutlierMultiplier
	}
	return 0
}

type ThresholdRecommendationsRequest struct {
	//
	//The parameters that are common to all close recommendations.
	RecRequest *CloseRecommendationRequest `protobuf:"bytes,1,opt,name=rec_request,json=recRequest,proto3" json:"rec_request,omitempty"`
	//
	//The threshold that recommendations will be calculated based on.
	//For uptime: ratio of uptime to observed lifetime beneath which channels
	//will be recommended for closure.
	//
	//For revenue: revenue per block that capital has been committed to the
	//channel beneath which channels will be recommended for closure. This
	//value is provided per block so that channels that have been open for
	//different periods of time can be compared.
	//
	//For incoming volume: The incoming volume per block that capital has
	//been committed to the channel beneath which channels will be recommended
	//for closure. This value is provided per block so that channels that have
	//been open for different periods of time can be compared.
	//
	//For outgoing volume: The outgoing volume per block that capital has been
	//committed to the channel beneath which channels will be recommended for
	//closure. This value is provided per block so that channels that have been
	//open for different periods of time can be compared.
	//
	//For total volume: The total volume per block that capital has been
	//committed to the channel beneath which channels will be recommended for
	//closure. This value is provided per block so that channels that have been
	//open for different periods of time can be compared.
	ThresholdValue       float32  `protobuf:"fixed32,2,opt,name=threshold_value,json=thresholdValue,proto3" json:"threshold_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThresholdRecommendationsRequest) Reset()         { *m = ThresholdRecommendationsRequest{} }
func (m *ThresholdRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ThresholdRecommendationsRequest) ProtoMessage()    {}
func (*ThresholdRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *ThresholdRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Unmarshal(m, b)
}
func (m *ThresholdRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ThresholdRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdRecommendationsRequest.Merge(m, src)
}
func (m *ThresholdRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ThresholdRecommendationsRequest.Size(m)
}
func (m *ThresholdRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdRecommendationsRequest proto.InternalMessageInfo

func (m *ThresholdRecommendationsRequest) GetRecRequest() *CloseRecommendationRequest {
	if m != nil {
		return m.RecRequest
	}
	return nil
}

func (m *ThresholdRecommendationsRequest) GetThresholdValue() float32 {
	if m != nil {
		return m.ThresholdValue
	}
	return 0
}

type CloseRecommendationsResponse struct {
	//
	//The total number of channels, before filtering out channels that are
	//not eligible for close recommendations.
	TotalChannels int32 `protobuf:"varint,1,opt,name=total_channels,json=totalChannels,proto3" json:"total_channels,omitempty"`
	//
	//The number of channels that were considered for close recommendations.
	ConsideredChannels int32 `protobuf:"varint,2,opt,name=considered_channels,json=consideredChannels,proto3" json:"considered_channels,omitempty"`
	//
	//A set of channel close recommendations. The absence of a channel in this
	//set implies that it was not considered for close because it did not meet
	//the criteria for close recommendations (it is private, or has not been
	//monitored for long enough).
	Recommendations      []*Recommendation `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CloseRecommendationsResponse) Reset()         { *m = CloseRecommendationsResponse{} }
func (m *CloseRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*CloseRecommendationsResponse) ProtoMessage()    {}
func (*CloseRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *CloseRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRecommendationsResponse.Unmarshal(m, b)
}
func (m *CloseRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *CloseRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRecommendationsResponse.Merge(m, src)
}
func (m *CloseRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_CloseRecommendationsResponse.Size(m)
}
func (m *CloseRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRecommendationsResponse proto.InternalMessageInfo

func (m *CloseRecommendationsResponse) GetTotalChannels() int32 {
	if m != nil {
		return m.TotalChannels
	}
	return 0
}

func (m *CloseRecommendationsResponse) GetConsideredChannels() int32 {
	if m != nil {
		return m.ConsideredChannels
	}
	return 0
}

func (m *CloseRecommendationsResponse) GetRecommendations() []*Recommendation {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

type Recommendation struct {
	//
	//The channel point [funding txid: outpoint] of the channel being considered
	//for close.
	ChanPoint string `protobuf:"bytes,1,opt,name=chan_point,json=chanPoint,proto3" json:"chan_point,omitempty"`
	// The value of the metric that close recommendations were based on.
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// A boolean indicating whether we recommend closing the channel.
	RecommendClose       bool     `protobuf:"varint,3,opt,name=recommend_close,json=recommendClose,proto3" json:"recommend_close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recommendation) Reset()         { *m = Recommendation{} }
func (m *Recommendation) String() string { return proto.CompactTextString(m) }
func (*Recommendation) ProtoMessage()    {}
func (*Recommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *Recommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation.Unmarshal(m, b)
}
func (m *Recommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation.Merge(m, src)
}
func (m *Recommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation.Size(m)
}
func (m *Recommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation proto.InternalMessageInfo

func (m *Recommendation) GetChanPoint() string {
	if m != nil {
		return m.ChanPoint
	}
	return ""
}

func (m *Recommendation) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Recommendation) GetRecommendClose() bool {
	if m != nil {
		return m.RecommendClose
	}
	return false
}

type RevenueReportRequest struct {
	//
	//The funding transaction outpoints for the channels to generate a revenue
	//report for. If this is empty, it will be generated for all open and closed
	//channels. Channel funding points should be expressed with the format
	//fundingTxID:outpoint.
	ChanPoints []string `protobuf:"bytes,1,rep,name=chan_points,json=chanPoints,proto3" json:"chan_points,omitempty"`
	//
	//Start time is beginning of the range over which the report will be
	//generated, expressed as unix epoch offset in seconds.
	StartTime uint64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	//
	//End time is end of the range over which the report will be
	//generated, expressed as unix epoch offset in seconds.
	EndTime              uint64   `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevenueReportRequest) Reset()         { *m = RevenueReportRequest{} }
func (m *RevenueReportRequest) String() string { return proto.CompactTextString(m) }
func (*RevenueReportRequest) ProtoMessage()    {}
func (*RevenueReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *RevenueReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReportRequest.Unmarshal(m, b)
}
func (m *RevenueReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReportRequest.Marshal(b, m, deterministic)
}
func (m *RevenueReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReportRequest.Merge(m, src)
}
func (m *RevenueReportRequest) XXX_Size() int {
	return xxx_messageInfo_RevenueReportRequest.Size(m)
}
func (m *RevenueReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReportRequest proto.InternalMessageInfo

func (m *RevenueReportRequest) GetChanPoints() []string {
	if m != nil {
		return m.ChanPoints
	}
	return nil
}

func (m *RevenueReportRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RevenueReportRequest) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type RevenueReportResponse struct {
	//
	//Reports is a set of pairwise revenue report generated for the channel(s)
	//over the period specified.
	Reports              []*RevenueReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RevenueReportResponse) Reset()         { *m = RevenueReportResponse{} }
func (m *RevenueReportResponse) String() string { return proto.CompactTextString(m) }
func (*RevenueReportResponse) ProtoMessage()    {}
func (*RevenueReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *RevenueReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReportResponse.Unmarshal(m, b)
}
func (m *RevenueReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReportResponse.Marshal(b, m, deterministic)
}
func (m *RevenueReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReportResponse.Merge(m, src)
}
func (m *RevenueReportResponse) XXX_Size() int {
	return xxx_messageInfo_RevenueReportResponse.Size(m)
}
func (m *RevenueReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReportResponse proto.InternalMessageInfo

func (m *RevenueReportResponse) GetReports() []*RevenueReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

type RevenueReport struct {
	//
	//Target channel is the channel that the report is generated for; incoming
	//fields in the report mean that this channel was the incoming channel,
	//and the pair as the outgoing, outgoing fields mean that this channel was
	//the outgoing channel and the peer was the incoming channel.
	TargetChannel string `protobuf:"bytes,1,opt,name=target_channel,json=targetChannel,proto3" json:"target_channel,omitempty"`
	//
	//Pair reports maps the channel point of a peer that we generated revenue
	//with to a report detailing the revenue.
	PairReports          map[string]*PairReport `protobuf:"bytes,2,rep,name=pair_reports,json=pairReports,proto3" json:"pair_reports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RevenueReport) Reset()         { *m = RevenueReport{} }
func (m *RevenueReport) String() string { return proto.CompactTextString(m) }
func (*RevenueReport) ProtoMessage()    {}
func (*RevenueReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *RevenueReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevenueReport.Unmarshal(m, b)
}
func (m *RevenueReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevenueReport.Marshal(b, m, deterministic)
}
func (m *RevenueReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevenueReport.Merge(m, src)
}
func (m *RevenueReport) XXX_Size() int {
	return xxx_messageInfo_RevenueReport.Size(m)
}
func (m *RevenueReport) XXX_DiscardUnknown() {
	xxx_messageInfo_RevenueReport.DiscardUnknown(m)
}

var xxx_messageInfo_RevenueReport proto.InternalMessageInfo

func (m *RevenueReport) GetTargetChannel() string {
	if m != nil {
		return m.TargetChannel
	}
	return ""
}

func (m *RevenueReport) GetPairReports() map[string]*PairReport {
	if m != nil {
		return m.PairReports
	}
	return nil
}

type PairReport struct {
	//
	//Amount outgoing msat is the amount in millisatoshis that arrived
	//on the pair channel to be forwarded onwards by our channel.
	AmountOutgoingMsat int64 `protobuf:"varint,1,opt,name=amount_outgoing_msat,json=amountOutgoingMsat,proto3" json:"amount_outgoing_msat,omitempty"`
	//
	//Fees outgoing is the amount of fees in millisatoshis that we
	//attribute to the channel for its role as the outgoing channel in
	//forwards.
	FeesOutgoingMsat int64 `protobuf:"varint,2,opt,name=fees_outgoing_msat,json=feesOutgoingMsat,proto3" json:"fees_outgoing_msat,omitempty"`
	//
	//Amount incoming msat is the amount in millisatoshis that arrived
	//on our channel to be forwarded onwards by the pair channel.
	AmountIncomingMsat int64 `protobuf:"varint,3,opt,name=amount_incoming_msat,json=amountIncomingMsat,proto3" json:"amount_incoming_msat,omitempty"`
	//
	//Fees incoming is the amount of fees in millisatoshis that we
	//attribute to the channel for its role as the incoming channel in
	//forwards.
	FeesIncomingMsat     int64    `protobuf:"varint,4,opt,name=fees_incoming_msat,json=feesIncomingMsat,proto3" json:"fees_incoming_msat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairReport) Reset()         { *m = PairReport{} }
func (m *PairReport) String() string { return proto.CompactTextString(m) }
func (*PairReport) ProtoMessage()    {}
func (*PairReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *PairReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairReport.Unmarshal(m, b)
}
func (m *PairReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairReport.Marshal(b, m, deterministic)
}
func (m *PairReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairReport.Merge(m, src)
}
func (m *PairReport) XXX_Size() int {
	return xxx_messageInfo_PairReport.Size(m)
}
func (m *PairReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PairReport.DiscardUnknown(m)
}

var xxx_messageInfo_PairReport proto.InternalMessageInfo

func (m *PairReport) GetAmountOutgoingMsat() int64 {
	if m != nil {
		return m.AmountOutgoingMsat
	}
	return 0
}

func (m *PairReport) GetFeesOutgoingMsat() int64 {
	if m != nil {
		return m.FeesOutgoingMsat
	}
	return 0
}

func (m *PairReport) GetAmountIncomingMsat() int64 {
	if m != nil {
		return m.AmountIncomingMsat
	}
	return 0
}

func (m *PairReport) GetFeesIncomingMsat() int64 {
	if m != nil {
		return m.FeesIncomingMsat
	}
	return 0
}

type ChannelInsightsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInsightsRequest) Reset()         { *m = ChannelInsightsRequest{} }
func (m *ChannelInsightsRequest) String() string { return proto.CompactTextString(m) }
func (*ChannelInsightsRequest) ProtoMessage()    {}
func (*ChannelInsightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *ChannelInsightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsightsRequest.Unmarshal(m, b)
}
func (m *ChannelInsightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsightsRequest.Marshal(b, m, deterministic)
}
func (m *ChannelInsightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsightsRequest.Merge(m, src)
}
func (m *ChannelInsightsRequest) XXX_Size() int {
	return xxx_messageInfo_ChannelInsightsRequest.Size(m)
}
func (m *ChannelInsightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsightsRequest proto.InternalMessageInfo

type ChannelInsightsResponse struct {
	// Insights for the set of currently open channels.
	ChannelInsights      []*ChannelInsight `protobuf:"bytes,1,rep,name=channel_insights,json=channelInsights,proto3" json:"channel_insights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelInsightsResponse) Reset()         { *m = ChannelInsightsResponse{} }
func (m *ChannelInsightsResponse) String() string { return proto.CompactTextString(m) }
func (*ChannelInsightsResponse) ProtoMessage()    {}
func (*ChannelInsightsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *ChannelInsightsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsightsResponse.Unmarshal(m, b)
}
func (m *ChannelInsightsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsightsResponse.Marshal(b, m, deterministic)
}
func (m *ChannelInsightsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsightsResponse.Merge(m, src)
}
func (m *ChannelInsightsResponse) XXX_Size() int {
	return xxx_messageInfo_ChannelInsightsResponse.Size(m)
}
func (m *ChannelInsightsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsightsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsightsResponse proto.InternalMessageInfo

func (m *ChannelInsightsResponse) GetChannelInsights() []*ChannelInsight {
	if m != nil {
		return m.ChannelInsights
	}
	return nil
}

type ChannelInsight struct {
	// The outpoint of the channel's funding transaction.
	ChanPoint string `protobuf:"bytes,1,opt,name=chan_point,json=chanPoint,proto3" json:"chan_point,omitempty"`
	//
	//The amount of time in seconds that we have monitored the channel peer's
	//uptime for.
	MonitoredSeconds uint64 `protobuf:"varint,2,opt,name=monitored_seconds,json=monitoredSeconds,proto3" json:"monitored_seconds,omitempty"`
	//
	//The amount of time in seconds that the channel peer has been online over
	//the period it has been monitored for.
	UptimeSeconds uint64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	//
	//The volume, in millisatoshis, that has been forwarded with this channel as
	//the incoming channel.
	VolumeIncomingMsat int64 `protobuf:"varint,4,opt,name=volume_incoming_msat,json=volumeIncomingMsat,proto3" json:"volume_incoming_msat,omitempty"`
	//
	//The volume, in millisatoshis, that has been forwarded with this channel as
	//the outgoing channel.
	VolumeOutgoingMsat int64 `protobuf:"varint,5,opt,name=volume_outgoing_msat,json=volumeOutgoingMsat,proto3" json:"volume_outgoing_msat,omitempty"`
	//
	//The total fees earned by this channel for its participation in forwards,
	//expressed in millisatoshis. Note that we attribute fees evenly across
	//incoming and outgoing channels.
	FeesEarnedMsat int64 `protobuf:"varint,6,opt,name=fees_earned_msat,json=feesEarnedMsat,proto3" json:"fees_earned_msat,omitempty"`
	// The number of confirmations the funding transaction has.
	Confirmations uint32 `protobuf:"varint,7,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	// True if the channel is private.
	Private              bool     `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInsight) Reset()         { *m = ChannelInsight{} }
func (m *ChannelInsight) String() string { return proto.CompactTextString(m) }
func (*ChannelInsight) ProtoMessage()    {}
func (*ChannelInsight) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *ChannelInsight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInsight.Unmarshal(m, b)
}
func (m *ChannelInsight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInsight.Marshal(b, m, deterministic)
}
func (m *ChannelInsight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInsight.Merge(m, src)
}
func (m *ChannelInsight) XXX_Size() int {
	return xxx_messageInfo_ChannelInsight.Size(m)
}
func (m *ChannelInsight) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInsight.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInsight proto.InternalMessageInfo

func (m *ChannelInsight) GetChanPoint() string {
	if m != nil {
		return m.ChanPoint
	}
	return ""
}

func (m *ChannelInsight) GetMonitoredSeconds() uint64 {
	if m != nil {
		return m.MonitoredSeconds
	}
	return 0
}

func (m *ChannelInsight) GetUptimeSeconds() uint64 {
	if m != nil {
		return m.UptimeSeconds
	}
	return 0
}

func (m *ChannelInsight) GetVolumeIncomingMsat() int64 {
	if m != nil {
		return m.VolumeIncomingMsat
	}
	return 0
}

func (m *ChannelInsight) GetVolumeOutgoingMsat() int64 {
	if m != nil {
		return m.VolumeOutgoingMsat
	}
	return 0
}

func (m *ChannelInsight) GetFeesEarnedMsat() int64 {
	if m != nil {
		return m.FeesEarnedMsat
	}
	return 0
}

func (m *ChannelInsight) GetConfirmations() uint32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *ChannelInsight) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func init() {
	proto.RegisterEnum("trmrpc.CloseRecommendationRequest_Metric", CloseRecommendationRequest_Metric_name, CloseRecommendationRequest_Metric_value)
	proto.RegisterType((*CloseRecommendationRequest)(nil), "trmrpc.CloseRecommendationRequest")
	proto.RegisterType((*OutlierRecommendationsRequest)(nil), "trmrpc.OutlierRecommendationsRequest")
	proto.RegisterType((*ThresholdRecommendationsRequest)(nil), "trmrpc.ThresholdRecommendationsRequest")
	proto.RegisterType((*CloseRecommendationsResponse)(nil), "trmrpc.CloseRecommendationsResponse")
	proto.RegisterType((*Recommendation)(nil), "trmrpc.Recommendation")
	proto.RegisterType((*RevenueReportRequest)(nil), "trmrpc.RevenueReportRequest")
	proto.RegisterType((*RevenueReportResponse)(nil), "trmrpc.RevenueReportResponse")
	proto.RegisterType((*RevenueReport)(nil), "trmrpc.RevenueReport")
	proto.RegisterMapType((map[string]*PairReport)(nil), "trmrpc.RevenueReport.PairReportsEntry")
	proto.RegisterType((*PairReport)(nil), "trmrpc.PairReport")
	proto.RegisterType((*ChannelInsightsRequest)(nil), "trmrpc.ChannelInsightsRequest")
	proto.RegisterType((*ChannelInsightsResponse)(nil), "trmrpc.ChannelInsightsResponse")
	proto.RegisterType((*ChannelInsight)(nil), "trmrpc.ChannelInsight")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xc7, 0x71, 0x9b, 0xb6, 0x2f, 0x9b, 0xd4, 0x3b, 0xdb, 0x2d, 0xa1, 0x6a, 0x69, 0x64, 0xed,
	0xb2, 0x41, 0x40, 0xba, 0x0a, 0x17, 0xc4, 0x89, 0xaa, 0x8a, 0x96, 0x88, 0x26, 0xa9, 0x66, 0x93,
	0x72, 0x41, 0xb2, 0x8c, 0x33, 0x9b, 0x0e, 0xc4, 0x33, 0xde, 0xf1, 0x38, 0xd2, 0x7e, 0x01, 0xae,
	0x1c, 0xf8, 0x32, 0x7c, 0x08, 0x2e, 0x1c, 0xf8, 0x2e, 0x1c, 0xd1, 0xfc, 0xb1, 0x1d, 0x87, 0x74,
	0xcb, 0x85, 0x9b, 0xe7, 0xf7, 0xfb, 0xcd, 0xfb, 0xcd, 0xbc, 0xf7, 0x32, 0x2f, 0x70, 0x20, 0x92,
	0xa8, 0x97, 0x08, 0x2e, 0x39, 0xaa, 0x4b, 0x11, 0x8b, 0x24, 0x3a, 0x39, 0x5d, 0x70, 0xbe, 0x58,
	0x92, 0x8b, 0x30, 0xa1, 0x17, 0x21, 0x63, 0x5c, 0x86, 0x92, 0x72, 0x96, 0x1a, 0x95, 0xff, 0xb7,
	0x03, 0x27, 0x57, 0x4b, 0x9e, 0x12, 0x4c, 0x22, 0x1e, 0xc7, 0x84, 0xcd, 0x35, 0x8d, 0xc9, 0xdb,
	0x8c, 0xa4, 0x12, 0x7d, 0x06, 0x8f, 0x63, 0xca, 0x68, 0x9c, 0xc5, 0x41, 0xcc, 0x19, 0x95, 0x5c,
	0x90, 0x79, 0xdb, 0xe9, 0x38, 0x5d, 0x17, 0x7b, 0x96, 0x18, 0xe5, 0x38, 0xba, 0x84, 0x7a, 0x4c,
	0xa4, 0xa0, 0x51, 0xbb, 0xd6, 0x71, 0xba, 0xad, 0xfe, 0xa7, 0x3d, 0x73, 0x84, 0xde, 0xfd, 0x06,
	0xbd, 0x91, 0xde, 0x80, 0xed, 0x46, 0xff, 0x27, 0xa8, 0x1b, 0x04, 0x35, 0x60, 0x6f, 0x36, 0xfe,
	0x6e, 0x3c, 0xf9, 0x7e, 0xec, 0x7d, 0x80, 0x00, 0xea, 0xb3, 0x9b, 0xe9, 0x70, 0x34, 0xf0, 0x1c,
	0x45, 0xe0, 0xc1, 0xed, 0x60, 0x3c, 0x1b, 0x78, 0x35, 0xf4, 0x04, 0x0e, 0x87, 0xe3, 0xab, 0xc9,
	0x68, 0x38, 0x7e, 0x15, 0xdc, 0x4e, 0xae, 0x67, 0xa3, 0x81, 0xe7, 0x2a, 0x70, 0x32, 0x9b, 0xbe,
	0x9a, 0xac, 0x81, 0x3b, 0xc8, 0x83, 0x47, 0xd3, 0xc9, 0xf4, 0xf2, 0x3a, 0x47, 0x76, 0xfd, 0xdf,
	0x1c, 0x38, 0x9b, 0x64, 0x72, 0x49, 0x89, 0xa8, 0x9e, 0x2d, 0xcd, 0x6f, 0x7f, 0x05, 0x0d, 0x41,
	0xa2, 0x40, 0x98, 0xa5, 0xbe, 0x77, 0xa3, 0xef, 0x3f, 0x7c, 0x2b, 0x0c, 0x82, 0x44, 0x79, 0x90,
	0x2f, 0x00, 0x71, 0xe3, 0x12, 0xc4, 0xd9, 0x52, 0xd2, 0x44, 0x7d, 0xea, 0x0c, 0xd5, 0xf0, 0x63,
	0xcb, 0x8c, 0x0a, 0xc2, 0xff, 0xd5, 0x81, 0xf3, 0xe9, 0x9d, 0x20, 0xe9, 0x1d, 0x5f, 0xce, 0xff,
	0xcf, 0x73, 0xbd, 0x80, 0x43, 0x99, 0xfb, 0x04, 0xab, 0x70, 0x99, 0x11, 0x7b, 0xa8, 0x56, 0x01,
	0xdf, 0x2a, 0xd4, 0xff, 0xdd, 0x81, 0xd3, 0x2d, 0x31, 0x53, 0x4c, 0xd2, 0x84, 0xb3, 0x94, 0xa0,
	0xe7, 0xd0, 0x92, 0x5c, 0x86, 0xcb, 0x20, 0xba, 0x0b, 0x19, 0x23, 0xcb, 0x54, 0x9f, 0x68, 0x17,
	0x37, 0x35, 0x7a, 0x65, 0x41, 0x74, 0x01, 0x4f, 0x22, 0xce, 0x52, 0x3a, 0x27, 0x82, 0xcc, 0x4b,
	0x6d, 0x4d, 0x6b, 0x51, 0x49, 0x15, 0x1b, 0xbe, 0x81, 0x43, 0x51, 0xb5, 0x6c, 0xbb, 0x1d, 0xb7,
	0xdb, 0xe8, 0x1f, 0xe7, 0x57, 0xdd, 0xb8, 0xe5, 0xa6, 0xdc, 0x67, 0xd0, 0xaa, 0x4a, 0xd0, 0x19,
	0x80, 0x72, 0x0e, 0x12, 0x4e, 0x99, 0xc9, 0xdc, 0x01, 0x3e, 0x50, 0xc8, 0x8d, 0x02, 0xd0, 0x11,
	0xec, 0xae, 0xa7, 0xc2, 0x2c, 0x54, 0xaa, 0x8a, 0xc8, 0x41, 0xa4, 0x52, 0xd1, 0x76, 0x3b, 0x4e,
	0x77, 0x1f, 0xb7, 0x0a, 0x58, 0x27, 0xc8, 0x7f, 0x0b, 0x47, 0x98, 0xac, 0x08, 0xcb, 0x08, 0x26,
	0x09, 0x17, 0x32, 0xcf, 0xf5, 0x39, 0x34, 0x4a, 0x57, 0x95, 0x1e, 0xb7, 0x7b, 0x80, 0xa1, 0xb0,
	0x4d, 0xd5, 0xb1, 0x52, 0x19, 0x0a, 0x19, 0x48, 0x1a, 0x1b, 0xf3, 0x1d, 0x7c, 0xa0, 0x91, 0x29,
	0x8d, 0x09, 0xfa, 0x08, 0xf6, 0x95, 0xb5, 0x26, 0x5d, 0x4d, 0xee, 0x11, 0x36, 0x57, 0x94, 0xff,
	0x2d, 0x3c, 0xdd, 0xb0, 0xb4, 0x55, 0xb9, 0x80, 0x3d, 0xa1, 0x11, 0xe3, 0xd7, 0xe8, 0x3f, 0x2d,
	0xb3, 0xb6, 0xae, 0xcf, 0x55, 0xfe, 0x5f, 0x0e, 0x34, 0x2b, 0x94, 0x2e, 0x6c, 0x28, 0x16, 0x44,
	0xe6, 0xd5, 0xb2, 0x09, 0x6b, 0x1a, 0xd4, 0x16, 0x0a, 0x0d, 0xe1, 0x51, 0x12, 0x52, 0x11, 0xe4,
	0x76, 0x35, 0x6d, 0xf7, 0xc9, 0x56, 0xbb, 0xde, 0x4d, 0x48, 0x85, 0xf9, 0x4c, 0x07, 0x4c, 0x8a,
	0x77, 0xb8, 0x91, 0x94, 0xc8, 0x09, 0x06, 0x6f, 0x53, 0x80, 0x3c, 0x70, 0x7f, 0x26, 0xef, 0xac,
	0xb5, 0xfa, 0x44, 0xdd, 0xf5, 0x2a, 0x35, 0xfa, 0x28, 0x77, 0x2a, 0xb7, 0xda, 0xca, 0x7d, 0x5d,
	0xfb, 0xca, 0xf1, 0xff, 0x70, 0x00, 0x4a, 0x06, 0xbd, 0x84, 0xa3, 0x30, 0xe6, 0x19, 0x93, 0x01,
	0xcf, 0xe4, 0x82, 0x53, 0xb6, 0x08, 0xe2, 0x34, 0x94, 0xf6, 0x55, 0x43, 0x86, 0x9b, 0x58, 0x6a,
	0x94, 0x86, 0x12, 0x7d, 0x0e, 0xe8, 0x0d, 0x21, 0xe9, 0x86, 0xbe, 0x66, 0x5e, 0x41, 0xc5, 0x54,
	0xd4, 0x65, 0x7c, 0xca, 0x22, 0x1e, 0x17, 0x7a, 0x77, 0x3d, 0xfe, 0xd0, 0x52, 0x95, 0xf8, 0x55,
	0xfd, 0x4e, 0x19, 0x7f, 0x5d, 0xed, 0xb7, 0xe1, 0xd8, 0x26, 0x7e, 0xc8, 0x52, 0xba, 0xb8, 0x93,
	0xf9, 0xb3, 0xe0, 0xff, 0x00, 0x1f, 0xfe, 0x8b, 0xb1, 0xcd, 0x70, 0x09, 0x9e, 0x2d, 0x61, 0x40,
	0x2d, 0x67, 0xbb, 0xa2, 0xf8, 0x2d, 0x55, 0xb7, 0xe2, 0xc3, 0xa8, 0x1a, 0xca, 0xff, 0xb3, 0x06,
	0xad, 0xaa, 0xe6, 0xa1, 0x1f, 0x93, 0x1a, 0x1e, 0xf9, 0x70, 0x08, 0x52, 0x12, 0x71, 0x36, 0x4f,
	0x6d, 0x6f, 0x7b, 0x05, 0xf1, 0xda, 0xe0, 0xaa, 0xd7, 0xb2, 0x44, 0x35, 0x78, 0xa1, 0x34, 0x8d,
	0xde, 0x34, 0x68, 0x2e, 0x7b, 0x09, 0x47, 0x2b, 0xbe, 0xcc, 0x62, 0xb2, 0x35, 0x5b, 0xc8, 0x70,
	0x95, 0xec, 0x96, 0x3b, 0xaa, 0xf5, 0xdb, 0x5d, 0xdf, 0x51, 0xa9, 0x60, 0x17, 0x74, 0xd6, 0x03,
	0x12, 0x0a, 0x46, 0xe6, 0x46, 0x5d, 0xd7, 0xea, 0x96, 0xc2, 0x07, 0x1a, 0xd6, 0xca, 0x67, 0xd0,
	0x8c, 0x38, 0x7b, 0x43, 0x45, 0x6c, 0xdf, 0xa7, 0xbd, 0x8e, 0xd3, 0x6d, 0xe2, 0x2a, 0x88, 0xda,
	0xb0, 0x97, 0x08, 0xba, 0x0a, 0x25, 0x69, 0xef, 0xeb, 0x67, 0x23, 0x5f, 0xf6, 0x7f, 0x71, 0xc1,
	0x9b, 0x12, 0x11, 0x53, 0x16, 0x4a, 0x2e, 0x5e, 0x13, 0xb1, 0x22, 0x02, 0x11, 0x38, 0xde, 0x3e,
	0x96, 0xd0, 0xf3, 0xbc, 0x56, 0xef, 0x1d, 0x5b, 0x27, 0xcf, 0xde, 0x33, 0x09, 0xca, 0x96, 0xa0,
	0xd0, 0xbe, 0x6f, 0xce, 0xa0, 0x17, 0x79, 0x84, 0x07, 0x26, 0xd1, 0x7f, 0xb4, 0xba, 0xde, 0x7c,
	0x58, 0x4e, 0xb7, 0x3f, 0x45, 0x36, 0xe8, 0xd9, 0x3d, 0xac, 0x8d, 0x86, 0xe1, 0x70, 0xa3, 0xcd,
	0xd1, 0xc7, 0xdb, 0x9b, 0xb8, 0x38, 0xe6, 0xf9, 0xbd, 0xbc, 0x89, 0xf9, 0x63, 0x5d, 0xff, 0x1b,
	0xfa, 0xf2, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xdf, 0x60, 0xc4, 0x40, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TerminatorServerClient is the client API for TerminatorServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TerminatorServerClient interface {
	OutlierRecommendations(ctx context.Context, in *OutlierRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error)
	ThresholdRecommendations(ctx context.Context, in *ThresholdRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error)
	RevenueReport(ctx context.Context, in *RevenueReportRequest, opts ...grpc.CallOption) (*RevenueReportResponse, error)
	ChannelInsights(ctx context.Context, in *ChannelInsightsRequest, opts ...grpc.CallOption) (*ChannelInsightsResponse, error)
}

type terminatorServerClient struct {
	cc *grpc.ClientConn
}

func NewTerminatorServerClient(cc *grpc.ClientConn) TerminatorServerClient {
	return &terminatorServerClient{cc}
}

func (c *terminatorServerClient) OutlierRecommendations(ctx context.Context, in *OutlierRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error) {
	out := new(CloseRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/trmrpc.TerminatorServer/OutlierRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminatorServerClient) ThresholdRecommendations(ctx context.Context, in *ThresholdRecommendationsRequest, opts ...grpc.CallOption) (*CloseRecommendationsResponse, error) {
	out := new(CloseRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/trmrpc.TerminatorServer/ThresholdRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminatorServerClient) RevenueReport(ctx context.Context, in *RevenueReportRequest, opts ...grpc.CallOption) (*RevenueReportResponse, error) {
	out := new(RevenueReportResponse)
	err := c.cc.Invoke(ctx, "/trmrpc.TerminatorServer/RevenueReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminatorServerClient) ChannelInsights(ctx context.Context, in *ChannelInsightsRequest, opts ...grpc.CallOption) (*ChannelInsightsResponse, error) {
	out := new(ChannelInsightsResponse)
	err := c.cc.Invoke(ctx, "/trmrpc.TerminatorServer/ChannelInsights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerminatorServerServer is the server API for TerminatorServer service.
type TerminatorServerServer interface {
	OutlierRecommendations(context.Context, *OutlierRecommendationsRequest) (*CloseRecommendationsResponse, error)
	ThresholdRecommendations(context.Context, *ThresholdRecommendationsRequest) (*CloseRecommendationsResponse, error)
	RevenueReport(context.Context, *RevenueReportRequest) (*RevenueReportResponse, error)
	ChannelInsights(context.Context, *ChannelInsightsRequest) (*ChannelInsightsResponse, error)
}

func RegisterTerminatorServerServer(s *grpc.Server, srv TerminatorServerServer) {
	s.RegisterService(&_TerminatorServer_serviceDesc, srv)
}

func _TerminatorServer_OutlierRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutlierRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminatorServerServer).OutlierRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trmrpc.TerminatorServer/OutlierRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminatorServerServer).OutlierRecommendations(ctx, req.(*OutlierRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminatorServer_ThresholdRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThresholdRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminatorServerServer).ThresholdRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trmrpc.TerminatorServer/ThresholdRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminatorServerServer).ThresholdRecommendations(ctx, req.(*ThresholdRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminatorServer_RevenueReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevenueReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminatorServerServer).RevenueReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trmrpc.TerminatorServer/RevenueReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminatorServerServer).RevenueReport(ctx, req.(*RevenueReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminatorServer_ChannelInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminatorServerServer).ChannelInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trmrpc.TerminatorServer/ChannelInsights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminatorServerServer).ChannelInsights(ctx, req.(*ChannelInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TerminatorServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trmrpc.TerminatorServer",
	HandlerType: (*TerminatorServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OutlierRecommendations",
			Handler:    _TerminatorServer_OutlierRecommendations_Handler,
		},
		{
			MethodName: "ThresholdRecommendations",
			Handler:    _TerminatorServer_ThresholdRecommendations_Handler,
		},
		{
			MethodName: "RevenueReport",
			Handler:    _TerminatorServer_RevenueReport_Handler,
		},
		{
			MethodName: "ChannelInsights",
			Handler:    _TerminatorServer_ChannelInsights_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
